<?php
/* これは文字化け防止のための日本語文字列です。
   このソースファイルは Shift_JIS で保存されています。
   Above is a Japanese strings to avoid charset mis-understanding.
   This source file is saved with Shift_JIS.

   ***** DO NOT EDIT THIS FILE WITH WORDPRESS ADMIN PANEL *****
*/

/* ==================================================
 *   KtaiService_Softbank class
   ================================================== */

class KtaiService_Softbank extends KtaiServices {
	protected $pict_sjis;

/* ==================================================
 * @param	string  $user_agent
 * @return	object  $this
 */
public function __construct($user_agent) {
	parent::__construct($user_agent);
	$this->operator = 'SoftBank';
	$this->use_redir = true;
	$this->show_plugin_icon = false;
	$this->pcview_enabled = false;
	$this->charset = 'SJIS-win';
	$this->mime_type = 'text/html';
	// http://creation.mb.softbank.jp/web/web_pic_about.html
	$this->num_chars = array('G' => 90, 'E' => 90, 'F' => 90, 'O' => 77, 'P' => 76, 'Q' => 62);

	// https://creation.mb.softbank.jp/web/web_ip.html
	// Last Update: 2011-02-10
	$this->networks = array(
		'123.108.237.0/27', 
		'202.253.96.224/27', 
		'210.146.7.192/26', 
/*
		'123.108.236.0/24', // Deleted
		'202.179.204.0/24', // Deleted
		'210.151.9.128/26', // Deleted
		'210.169.130.112/28', // Deleted
		'210.228.189.0/24', // Deleted
		'211.8.159.128/25', // Deleted
		'210.146.60.192/26', // Deleted
		'210.175.1.128/25', // Deleted
 */
 	);
	// http://creation.mb.softbank.jp/download.php?docid=103 (members only)
	$this->pict_sjis = array(
		'se001' => "\xf9\x41", // 男の子
		'se002' => "\xf9\x42", // 女の子
		'se003' => "\xf9\x43", // 美容 (キスマーク)
		'se004' => "\xf9\x44", // お父さん
		'se005' => "\xf9\x45", // お母さん
		'se006' => "\xf9\x46", // 洋服
		'se007' => "\xf9\x47", // ブーツ
		'se008' => "\xf9\x48", // カメラ
		'se009' => "\xf9\x49", // 電話
		'se00a' => "\xf9\x4a", // 携帯電話
		'se00b' => "\xf9\x4b", // FAX
		'se00c' => "\xf9\x4c", // パソコン
		'se00d' => "\xf9\x4d", // パンチ
		'se00e' => "\xf9\x4e", // GOOD!
		'se00f' => "\xf9\x4f", // No.1!
		'se010' => "\xf9\x50", // グー
		'se011' => "\xf9\x51", // チョキ
		'se012' => "\xf9\x52", // パー
		'se013' => "\xf9\x53", // スキー
		'se014' => "\xf9\x54", // ゴルフ
		'se015' => "\xf9\x55", // テニス
		'se016' => "\xf9\x56", // 野球
		'se017' => "\xf9\x57", // サーフィン
		'se018' => "\xf9\x58", // サッカー
		'se019' => "\xf9\x59", // 魚
		'se01a' => "\xf9\x5a", // うま
		'se01b' => "\xf9\x5b", // 車
		'se01c' => "\xf9\x5c", // ヨット
		'se01d' => "\xf9\x5d", // 飛行機
		'se01e' => "\xf9\x5e", // 電車
		'se01f' => "\xf9\x5f", // 新幹線
		'se020' => "\xf9\x60", // ハテナ
		'se021' => "\xf9\x61", // ビックリ
		'se022' => "\xf9\x62", // ハートマーク
		'se023' => "\xf9\x63", // ハートブレイク
		'se024' => "\xf9\x64", // 1時
		'se025' => "\xf9\x65", // 2時
		'se026' => "\xf9\x66", // 時計
		'se027' => "\xf9\x67", // 4時
		'se028' => "\xf9\x68", // 5時
		'se029' => "\xf9\x69", // 6時
		'se02a' => "\xf9\x6a", // 7時
		'se02b' => "\xf9\x6b", // 8時
		'se02c' => "\xf9\x6c", // 9時
		'se02d' => "\xf9\x6d", // 10時
		'se02e' => "\xf9\x6e", // 11時
		'se02f' => "\xf9\x6f", // 12時
		'se030' => "\xf9\x70", // お花見
		'se031' => "\xf9\x71", // エンブレム
		'se032' => "\xf9\x72", // バラ
		'se033' => "\xf9\x73", // クリスマス
		'se034' => "\xf9\x74", // 指輪
		'se035' => "\xf9\x75", // 宝石
		'se036' => "\xf9\x76", // 家
		'se037' => "\xf9\x77", // 教会
		'se038' => "\xf9\x78", // ビル
		'se039' => "\xf9\x79", // 駅
		'se03a' => "\xf9\x7a", // ガソリンスタンド
		'se03b' => "\xf9\x7b", // 山
		'se03c' => "\xf9\x7c", // マイク
		'se03d' => "\xf9\x7d", // 映画
		'se03e' => "\xf9\x7e", // 音楽 (音符)
		'se03f' => "\xf9\x80", // カギ
		'se040' => "\xf9\x81", // サックス
		'se041' => "\xf9\x82", // ギター
		'se042' => "\xf9\x83", // トランペット
		'se043' => "\xf9\x84", // レストラン
		'se044' => "\xf9\x85", // カクテル
		'se045' => "\xf9\x86", // コーヒー
		'se046' => "\xf9\x87", // ケーキ
		'se047' => "\xf9\x88", // ビール
		'se048' => "\xf9\x89", // 雪
		'se049' => "\xf9\x8a", // 曇り
		'se04a' => "\xf9\x8b", // 晴れ (昼)
		'se04b' => "\xf9\x8c", // 雨
		'se04c' => "\xf9\x8d", // 晴れ (夜)
		'se04d' => "\xf9\x8e", // 朝
		'se04e' => "\xf9\x8f", // 天使
		'se04f' => "\xf9\x90", // ねこ
		'se050' => "\xf9\x91", // とら
		'se051' => "\xf9\x92", // くま
		'se052' => "\xf9\x93", // いぬ
		'se053' => "\xf9\x94", // ねずみ
		'se054' => "\xf9\x95", // クジラ
		'se055' => "\xf9\x96", // ペンギン
		'se056' => "\xf9\x97", // 楽 (顔)
		'se057' => "\xf9\x98", // 喜 (顔)
		'se058' => "\xf9\x99", // 哀 (顔)
		'se059' => "\xf9\x9a", // 怒 (顔)
		'se05a' => "\xf9\x9b", // ウンチ
		'se101' => "\xf7\x41", // メール受信
		'se102' => "\xf7\x42", // メール送信
		'se103' => "\xf7\x43", // メール宛先
		'se104' => "\xf7\x44", // 電話連絡先
		'se105' => "\xf7\x45", // アカンベー (顔)
		'se106' => "\xf7\x46", // ラブラブ (顔)
		'se107' => "\xf7\x47", // ガビーン (顔)
		'se108' => "\xf7\x48", // タラー (顔)
		'se109' => "\xf7\x49", // さる
		'se10a' => "\xf7\x4a", // タコ
		'se10b' => "\xf7\x4b", // ぶた
		'se10c' => "\xf7\x4c", // 宇宙人
		'se10d' => "\xf7\x4d", // ロケット
		'se10e' => "\xf7\x4e", // 王冠
		'se10f' => "\xf7\x4f", // 電球
		'se110' => "\xf7\x50", // よつば
		'se111' => "\xf7\x51", // キス
		'se112' => "\xf7\x52", // バースデー (プレゼント)
		'se113' => "\xf7\x53", // ピストル
		'se114' => "\xf7\x54", // 虫眼鏡
		'se115' => "\xf7\x55", // 陸上
		'se116' => "\xf7\x56", // オークション
		'se117' => "\xf7\x57", // 花火
		'se118' => "\xf7\x58", // もみじ
		'se119' => "\xf7\x59", // 落ち葉
		'se11a' => "\xf7\x5a", // 悪魔
		'se11b' => "\xf7\x5b", // おばけ
		'se11c' => "\xf7\x5c", // ドクロ
		'se11d' => "\xf7\x5d", // ファイヤー
		'se11e' => "\xf7\x5e", // かばん
		'se11f' => "\xf7\x5f", // 座席
		'se120' => "\xf7\x60", // ハンバーガー
		'se121' => "\xf7\x61", // 公園
		'se122' => "\xf7\x62", // キャンプ場
		'se123' => "\xf7\x63", // 温泉
		'se124' => "\xf7\x64", // 遊園地
		'se125' => "\xf7\x65", // チケット
		'se126' => "\xf7\x66", // CD
		'se127' => "\xf7\x67", // DVD
		'se128' => "\xf7\x68", // ラジオ
		'se129' => "\xf7\x69", // ビデオ
		'se12a' => "\xf7\x6a", // テレビ
		'se12b' => "\xf7\x6b", // ゲーム
		'se12c' => "\xf7\x6c", // 歌い出し
		'se12d' => "\xf7\x6d", // マージャン
		'se12e' => "\xf7\x6e", // 対決
		'se12f' => "\xf7\x6f", // 賞金 (ドル袋)
		'se130' => "\xf7\x70", // 当たり
		'se131' => "\xf7\x71", // トロフィー
		'se132' => "\xf7\x72", // ゴール (チェッカーフラッグ)
		'se133' => "\xf7\x73", // スロット (777)
		'se134' => "\xf7\x74", // 競馬
		'se135' => "\xf7\x75", // 競艇
		'se136' => "\xf7\x76", // 競輪
		'se137' => "\xf7\x77", // 工事中
		'se138' => "\xf7\x78", // 男性
		'se139' => "\xf7\x79", // 女性
		'se13a' => "\xf7\x7a", // 乳幼児
		'se13b' => "\xf7\x7b", // 注射器
		'se13c' => "\xf7\x7c", // 睡眠 (Zzz)
		'se13d' => "\xf7\x7d", // 雷
		'se13e' => "\xf7\x7e", // ハイヒール
		'se13f' => "\xf7\x80", // 入浴
		'se140' => "\xf7\x81", // トイレ
		'se141' => "\xf7\x82", // 音声
		'se142' => "\xf7\x83", // お知らせ (メガホン)
		'se143' => "\xf7\x84", // 祝日
		'se144' => "\xf7\x85", // ロックON
		'se145' => "\xf7\x86", // ロックOFF
		'se146' => "\xf7\x87", // 街
		'se147' => "\xf7\x88", // 料理 (卵)
		'se148' => "\xf7\x89", // 本
		'se149' => "\xf7\x8a", // 為替相場
		'se14a' => "\xf7\x8b", // 株価
		'se14b' => "\xf7\x8c", // ニュース (パラボラアンテナ)
		'se14c' => "\xf7\x8d", // 元気 (力こぶ)
		'se14d' => "\xf7\x8e", // 銀行
		'se14e' => "\xf7\x8f", // 信号
		'se14f' => "\xf7\x90", // 駐車場
		'se150' => "\xf7\x91", // バス停
		'se151' => "\xf7\x92", // 公衆トイレ
		'se152' => "\xf7\x93", // 交番
		'se153' => "\xf7\x94", // 郵便局
		'se154' => "\xf7\x95", // ATM
		'se155' => "\xf7\x96", // 病院
		'se156' => "\xf7\x97", // コンビニ
		'se157' => "\xf7\x98", // 学校
		'se158' => "\xf7\x99", // ホテル
		'se159' => "\xf7\x9a", // バス
		'se15a' => "\xf7\x9b", // タクシー
		'se201' => "\xf7\xa1", // 徒歩
		'se202' => "\xf7\xa2", // 船
		'se203' => "\xf7\xa3", // 目的地 (ココ)
		'se204' => "\xf7\xa4", // 飾罫1
		'se205' => "\xf7\xa5", // 飾罫2
		'se206' => "\xf7\xa6", // 飾罫3
		'se207' => "\xf7\xa7", // 18禁
		'se208' => "\xf7\xa8", // 禁煙
		'se209' => "\xf7\xa9", // 初心者
		'se20a' => "\xf7\xaa", // バリアフリー (車椅子マーク)
		'se20b' => "\xf7\xab", // アンテナマーク
		'se20c' => "\xf7\xac", // ハート (トランプ)
		'se20d' => "\xf7\xad", // ダイヤ (トランプ)
		'se20e' => "\xf7\xae", // スペード (トランプ)
		'se20f' => "\xf7\xaf", // クラブ (トランプ)
		'se210' => "\xf7\xb0", // シャープダイヤル
		'se211' => "\xf7\xb1", // フリーダイヤル
		'se212' => "\xf7\xb2", // 新着
		'se213' => "\xf7\xb3", // 更新
		'se214' => "\xf7\xb4", // おすすめ (COOL)
		'se215' => "\xf7\xb5", // 有料
		'se216' => "\xf7\xb6", // 無料
		'se217' => "\xf7\xb7", // 月額
		'se218' => "\xf7\xb8", // 申し込み
		'se219' => "\xf7\xb9", // 見出しボタン1 (オレンジ)
		'se21a' => "\xf7\xba", // 見出しボタン2 (緑)
		'se21b' => "\xf7\xbb", // 見出しボタン4 (紫)
		'se21c' => "\xf7\xbc", // 1 (one)
		'se21d' => "\xf7\xbd", // 2 (two)
		'se21e' => "\xf7\xbe", // 3 (three)
		'se21f' => "\xf7\xbf", // 4 (four)
		'se220' => "\xf7\xc0", // 5 (five)
		'se221' => "\xf7\xc1", // 6 (six)
		'se222' => "\xf7\xc2", // 7 (seven)
		'se223' => "\xf7\xc3", // 8 (eight)
		'se224' => "\xf7\xc4", // 9 (nine)
		'se225' => "\xf7\xc5", // 0 (zero)
		'se226' => "\xf7\xc6", // お得
		'se227' => "\xf7\xc7", // 割引
		'se228' => "\xf7\xc8", // サービス料
		'se229' => "\xf7\xc9", // ID
		'se22a' => "\xf7\xca", // 満席
		'se22b' => "\xf7\xcb", // 空席
		'se22c' => "\xf7\xcc", // 指定席
		'se22d' => "\xf7\xcd", // 営業時間
		'se22e' => "\xf7\xce", // 上へ (指)
		'se22f' => "\xf7\xcf", // 下へ (指)
		'se230' => "\xf7\xd0", // 左へ (指)
		'se231' => "\xf7\xd1", // 右へ (指)
		'se232' => "\xf7\xd2", // 上
		'se233' => "\xf7\xd3", // 下
		'se234' => "\xf7\xd4", // 右
		'se235' => "\xf7\xd5", // 左
		'se236' => "\xf7\xd6", // 右上
		'se237' => "\xf7\xd7", // 左上
		'se238' => "\xf7\xd8", // 右下
		'se239' => "\xf7\xd9", // 左下
		'se23a' => "\xf7\xda", // 次へ
		'se23b' => "\xf7\xdb", // 前へ
		'se23c' => "\xf7\xdc", // 早送り 
		'se23d' => "\xf7\xdd", // 巻き戻し
		'se23e' => "\xf7\xde", // 星座
		'se23f' => "\xf7\xdf", // おひつじ座
		'se240' => "\xf7\xe0", // おうし座
		'se241' => "\xf7\xe1", // ふたご座
		'se242' => "\xf7\xe2", // かに座
		'se243' => "\xf7\xe3", // しし座
		'se244' => "\xf7\xe4", // おとめ座
		'se245' => "\xf7\xe5", // てんぴん座
		'se246' => "\xf7\xe6", // さそり座
		'se247' => "\xf7\xe7", // いて座
		'se248' => "\xf7\xe8", // やぎ座
		'se249' => "\xf7\xe9", // みずがめ座
		'se24a' => "\xf7\xea", // うお座
		'se24b' => "\xf7\xeb", // へびつかい座
		'se24c' => "\xf7\xec", // TOPページ
		'se24d' => "\xf7\xed", // OKボタン
		'se24e' => "\xf7\xee", // 著作権 (C)
		'se24f' => "\xf7\xef", // 登録商標 (R)
		'se250' => "\xf7\xf0", // マナーモード
		'se251' => "\xf7\xf1", // 電源切
		'se252' => "\xf7\xf2", // ご注意 (!)
		'se253' => "\xf7\xf3", // ご案内
		'se254' => "\xf7\xf4", // J-PHONEショップ
		'se255' => "\xf7\xf5", // スカイウェブ
		'se256' => "\xf7\xf6", // スカイウォーカー
		'se257' => "\xf7\xf7", // スカイメロディ
		'se258' => "\xf7\xf8", // J-PHONE 1
		'se259' => "\xf7\xf9", // J-PHONE 2
		'se25a' => "\xf7\xfa", // J-PHONE 3
		'se301' => "\xf9\xa1", // メモ
		'se302' => "\xf9\xa2", // ネクタイ
		'se303' => "\xf9\xa3", // ハイビスカス
		'se304' => "\xf9\xa4", // チューリップ
		'se305' => "\xf9\xa5", // ひまわり
		'se306' => "\xf9\xa6", // 花束
		'se307' => "\xf9\xa7", // やしの木
		'se308' => "\xf9\xa8", // サボテン
		'se309' => "\xf9\xa9", // トイレ
		'se30a' => "\xf9\xaa", // ヘッドホン
		'se30b' => "\xf9\xab", // 晩酌 (とっくり)
		'se30c' => "\xf9\xac", // 乾杯 (ビール)
		'se30d' => "\xf9\xad", // 祝
		'se30e' => "\xf9\xae", // 喫煙
		'se30f' => "\xf9\xaf", // カプセル薬
		'se310' => "\xf9\xb0", // 風船
		'se311' => "\xf9\xb1", // 爆弾
		'se312' => "\xf9\xb2", // クラッカー
		'se313' => "\xf9\xb3", // ハサミ
		'se314' => "\xf9\xb4", // リボン
		'se315' => "\xf9\xb5", // マル秘
		'se316' => "\xf9\xb6", // MD
		'se317' => "\xf9\xb7", // メガフォン
		'se318' => "\xf9\xb8", // 帽子
		'se319' => "\xf9\xb9", // 可愛いワンピース
		'se31a' => "\xf9\xba", // ミュール
		'se31b' => "\xf9\xbb", // ロングブーツ
		'se31c' => "\xf9\xbc", // 口紅
		'se31d' => "\xf9\xbd", // マニキュア
		'se31e' => "\xf9\xbe", // エステ
		'se31f' => "\xf9\xbf", // 美容院
		'se320' => "\xf9\xc0", // 理髪店
		'se321' => "\xf9\xc1", // 着物
		'se322' => "\xf9\xc2", // ビキニ
		'se323' => "\xf9\xc3", // ブランドバッグ
		'se324' => "\xf9\xc4", // カチンコ
		'se325' => "\xf9\xc5", // すず
		'se326' => "\xf9\xc6", // 踊る音符
		'se327' => "\xf9\xc7", // ぴかぴかハート
		'se328' => "\xf9\xc8", // ドキドキハート
		'se329' => "\xf9\xc9", // ハートを射とめて
		'se32a' => "\xf9\xca", // ハート (青)
		'se32b' => "\xf9\xcb", // ハート (緑)
		'se32c' => "\xf9\xcc", // ハート (黄)
		'se32d' => "\xf9\xcd", // ハート (紫)
		'se32e' => "\xf9\xce", // NEW (ぴかぴか)
		'se32f' => "\xf9\xcf", // ☆
		'se330' => "\xf9\xd0", // ダッシュ
		'se331' => "\xf9\xd1", // 飛び散る汗
		'se332' => "\xf9\xd2", // ○
		'se333' => "\xf9\xd3", // ×
		'se334' => "\xf9\xd4", // 怒り
		'se335' => "\xf9\xd5", // ☆ (点滅)
		'se336' => "\xf9\xd6", // 動く "?"
		'se337' => "\xf9\xd7", // 動く "!"
		'se338' => "\xf9\xd8", // お茶
		'se339' => "\xf9\xd9", // パン
		'se33a' => "\xf9\xda", // ソフトクリーム
		'se33b' => "\xf9\xdb", // フライドポテト
		'se33c' => "\xf9\xdc", // 串団子 
		'se33d' => "\xf9\xdd", // せんべい
		'se33e' => "\xf9\xde", // ご飯
		'se33f' => "\xf9\xdf", // スパゲティ
		'se340' => "\xf9\xe0", // ラーメン
		'se341' => "\xf9\xe1", // カレーライス
		'se342' => "\xf9\xe2", // おにぎり
		'se343' => "\xf9\xe3", // おでん
		'se344' => "\xf9\xe4", // 寿司
		'se345' => "\xf9\xe5", // りんご
		'se346' => "\xf9\xe6", // みかん
		'se347' => "\xf9\xe7", // いちご
		'se348' => "\xf9\xe8", // すいか
		'se349' => "\xf9\xe9", // トマト
		'se34a' => "\xf9\xea", // なす
		'se34b' => "\xf9\xeb", // バースデーケーキ
		'se34c' => "\xf9\xec", // 駅弁
		'se34d' => "\xf9\xed", // ナベ
		'se401' => "\xfb\x41", // あせり (顔)
		'se402' => "\xfb\x42", // ほそくんでいる (顔)
		'se403' => "\xfb\x43", // ひたすらごめんなさい (顔)
		'se404' => "\xfb\x44", // えっへん (顔)
		'se405' => "\xfb\x45", // ウィンク (顔)
		'se406' => "\xfb\x46", // わさびがきいた (顔)
		'se407' => "\xfb\x47", // 目がぐるぐる (顔)
		'se408' => "\xfb\x48", // 鼻ちょうちん (顔)
		'se409' => "\xfb\x49", // あっかんべー (顔)
		'se40a' => "\xfb\x4a", // 酔っ払い (顔)
		'se40b' => "\xfb\x4b", // ゲロゲロ (顔)
		'se40c' => "\xfb\x4c", // マスクをつけた顔
		'se40d' => "\xfb\x4d", // 顔があかくなる
		'se40e' => "\xfb\x4e", // しらけ顔
		'se40f' => "\xfb\x4f", // 冷や汗 (顔)
		'se410' => "\xfb\x50", // びっくり (顔)
		'se411' => "\xfb\x51", // 泣き (顔)
		'se412' => "\xfb\x52", // 泣いたり笑ったり (顔)
		'se413' => "\xfb\x53", // 可愛く泣いてる人
		'se414' => "\xfb\x54", // にこにこ (顔)
		'se415' => "\xfb\x55", // あははと笑う (顔)
		'se416' => "\xfb\x56", // めちゃめちゃ怒っている (顔)
		'se417' => "\xfb\x57", // KISS:動く口
		'se418' => "\xfb\x58", // 投げKISS
		'se419' => "\xfb\x59", // 目
		'se41a' => "\xfb\x5a", // 鼻
		'se41b' => "\xfb\x5b", // 耳
		'se41c' => "\xfb\x5c", // 口
		'se41d' => "\xfb\x5d", // ごめんなさい (合わせた手)
		'se41e' => "\xfb\x5e", // バイバイ (手を振る)
		'se41f' => "\xfb\x5f", // 拍手
		'se420' => "\xfb\x60", // OK (指で丸サイン)
		'se421' => "\xfb\x61", // Booing (親指を下)
		'se422' => "\xfb\x62", // おっは～
		'se423' => "\xfb\x63", // × (両腕をクロス)
		'se424' => "\xfb\x64", // ○ (両腕を頭に)
		'se425' => "\xfb\x65", // 手をつないでいる
		'se426' => "\xfb\x66", // 土下座
		'se427' => "\xfb\x67", // バンザイ
		'se428' => "\xfb\x68", // 人と人が歩いている
		'se429' => "\xfb\x69", // ラインダンス (バニーガール)
		'se42a' => "\xfb\x6a", // バスケットボール
		'se42b' => "\xfb\x6b", // フットボール
		'se42c' => "\xfb\x6c", // ビリヤード
		'se42d' => "\xfb\x6d", // 水泳
		'se42e' => "\xfb\x6e", // RV車
		'se42f' => "\xfb\x6f", // トラック
		'se430' => "\xfb\x70", // 消防車
		'se431' => "\xfb\x71", // 救急車
		'se432' => "\xfb\x72", // パトカー
		'se433' => "\xfb\x73", // ジェットコースター
		'se434' => "\xfb\x74", // 地下鉄
		'se435' => "\xfb\x75", // 新幹線(700系)
		'se436' => "\xfb\x76", // 門松
		'se437' => "\xfb\x77", // チョコ
		'se438' => "\xfb\x78", // お雛様
		'se439' => "\xfb\x79", // 卒業式
		'se43a' => "\xfb\x7a", // ランドセル
		'se43b' => "\xfb\x7b", // 鯉のぼり
		'se43c' => "\xfb\x7c", // とじかさ
		'se43d' => "\xfb\x7d", // 結婚式
		'se43e' => "\xfb\x7e", // 波がザーン
		'se43f' => "\xfb\x80", // かき氷
		'se440' => "\xfb\x81", // 線香花火
		'se441' => "\xfb\x82", // 貝
		'se442' => "\xfb\x83", // 風鈴
		'se443' => "\xfb\x84", // 台風
		'se444' => "\xfb\x85", // 稲穂
		'se445' => "\xfb\x86", // ハロウィン
		'se446' => "\xfb\x87", // お月見
		'se447' => "\xfb\x88", // 風がビュー
		'se448' => "\xfb\x89", // サンタクロース
		'se449' => "\xfb\x8a", // 朝日
		'se44a' => "\xfb\x8b", // 夕日
		'se44b' => "\xfb\x8c", // 流れ星
		'se44c' => "\xfb\x8d", // 虹
		'se501' => "\xfb\xa1", // ラブホテル
		'se502' => "\xfb\xa2", // アート
		'se503' => "\xfb\xa3", // 演劇
		'se504' => "\xfb\xa4", // デパート
		'se505' => "\xfb\xa5", // お城 (和)
		'se506' => "\xfb\xa6", // お城 (洋)
		'se507' => "\xfb\xa7", // 映画館
		'se508' => "\xfb\xa8", // 工場
		'se509' => "\xfb\xa9", // 東京タワー
		'se50a' => "\xfb\xaa", // 109
		'se50b' => "\xfb\xab", // 日本 (国旗)
		'se50c' => "\xfb\xac", // アメリカ (国旗)
		'se50d' => "\xfb\xad", // フランス (国旗)
		'se50e' => "\xfb\xae", // ドイツ (国旗)
		'se50f' => "\xfb\xaf", // イタリア (国旗)
		'se510' => "\xfb\xb0", // イギリス (国旗)
		'se511' => "\xfb\xb1", // スペイン (国旗)
		'se512' => "\xfb\xb2", // ロシア (国旗)
		'se513' => "\xfb\xb3", // 中国 (国旗)
		'se514' => "\xfb\xb4", // 韓国 (国旗)
		'se515' => "\xfb\xb5", // 白人
		'se516' => "\xfb\xb6", // 中国人
		'se517' => "\xfb\xb7", // インド人
		'se518' => "\xfb\xb8", // おじいちゃん
		'se519' => "\xfb\xb9", // おばあちゃん
		'se51a' => "\xfb\xba", // あかちゃん
		'se51b' => "\xfb\xbb", // 安全第一
		'se51c' => "\xfb\xbc", // お姫さま
		'se51d' => "\xfb\xbd", // 自由の女神
		'se51e' => "\xfb\xbe", // 衛兵
		'se51f' => "\xfb\xbf", // フラメンコ
		'se520' => "\xfb\xc0", // イルカ
		'se521' => "\xfb\xc1", // とり
		'se522' => "\xfb\xc2", // 熱帯魚
		'se523' => "\xfb\xc3", // ひよこ
		'se524' => "\xfb\xc4", // ハムスター
		'se525' => "\xfb\xc5", // けむし
		'se526' => "\xfb\xc6", // ぞう
		'se527' => "\xfb\xc7", // コアラ
		'se528' => "\xfb\xc8", // チンパンジー
		'se529' => "\xfb\xc9", // ひつじ
		'se52a' => "\xfb\xca", // おおかみ
		'se52b' => "\xfb\xcb", // うし
		'se52c' => "\xfb\xcc", // うさぎ
		'se52d' => "\xfb\xcd", // へび
		'se52e' => "\xfb\xce", // にわとり
		'se52f' => "\xfb\xcf", // いのしし
		'se530' => "\xfb\xd0", // らくだ
		'se531' => "\xfb\xd1", // かえる
		'se532' => "\xfb\xd2", // A型
		'se533' => "\xfb\xd3", // B型
		'se534' => "\xfb\xd4", // AB型
		'se535' => "\xfb\xd5", // O型
		'se536' => "\xfb\xd6", // 足あと
		'se537' => "\xfb\xd7", // TM (商標)
		'se538' => "\xfb\xd8", // J-Sky 1
		'se539' => "\xfb\xd9", // J-Sky 2
		'se53a' => "\xfb\xda", // Vodafone 1
		'se53b' => "\xfb\xdb", // Vodafone 2
		'se53c' => "\xfb\xdc", // Vodafone 3
		'se53d' => "\xfb\xdd", // Vodafone 4
		'se53e' => "\xfb\xde", // Vodafone 5
	);
	return;
}

/* ==================================================
 * @param	string  $buffer
 * @return	string  $buffer
 */
public function replace_smiley($buffer) {
	$smiles = array(
		'icon_smile.gif'     => $this->pictograms['se056'],
		'icon_biggrin.gif'   => $this->pictograms['se057'],
		'icon_sad.gif'       => $this->pictograms['se058'],
		'icon_surprised.gif' => $this->pictograms['se410'],
		'icon_eek.gif'       => $this->pictograms['se410'],
		'icon_confused.gif'  => $this->pictograms['se407'],
		'icon_cool.gif'      => $this->pictograms['se214'],
		'icon_mad.gif'       => $this->pictograms['se059'],
		'icon_razz.gif'      => $this->pictograms['se409'],
		'icon_neutral.gif'   => $this->pictograms['se402'],
		'icon_wink.gif'      => $this->pictograms['se405'],
		'icon_lol.gif'       => $this->pictograms['se409'],
		'icon_redface.gif'   => $this->pictograms['se40a'],
		'icon_cry.gif'       => $this->pictograms['se411'],
		'icon_evil.gif'      => $this->pictograms['se416'],
		'icon_twisted.gif'   => $this->pictograms['se416'],
		'icon_rolleyes.gif'  => $this->pictograms['se407'],
		'icon_exclaim.gif'   => $this->pictograms['se021'],
		'icon_question.gif'  => $this->pictograms['se020'],
		'icon_idea.gif'      => $this->pictograms['se10f'],
		'icon_arrow.gif'     => $this->pictograms['se234'],
		'icon_mrgreen.gif'   => $this->pictograms['se415'],
	);
	$smiles = apply_filters('ktai_smiley_table', $smiles, __CLASS__);
	return parent::replace_smiley($buffer, $smiles);
}

/* ==================================================
 * @param	string  $buffer
 * @return	string  $buffer
 *            http://www.au.kddi.com/ezfactory/tec/spec/3.html
 */
public function convert_pict($buffer) {
	// http://www.au.kddi.com/email/emoji/
	// http://mb.softbank.jp/mb/service/3G/mail/pictogram/
	// http://www.nttdocomo.co.jp/service/mail/imode_mail/emoji_convert/
	// http://www.willcom-inc.com/ja/service/e_mail/pdf/conversiontable.pdf
	$translated = $this->pictograms + array(
		'1'     => $this->pictograms['se252'], // 「!」
		'2'     => $this->pictograms['se337'], // 「!」
		'3'     => $this->pictograms['se336'], // 「?」
		'4'     => 'Q', // 「Q」
		'5'     => $this->pictograms['se23b'], // 左向き三角1
		'6'     => $this->pictograms['se23a'], // 右向き三角1
		'7'     => $this->pictograms['se23d'], // 左向き三角2
		'8'     => $this->pictograms['se23c'], // 右向き三角2
		'9'     => '□', // 小四角 1
		'10'    => '■', // 小四角 2
		'11'    => '[i]', // インフォメーションシンボル
		'12'    => $this->pictograms['se044'], // ワイングラス
		'13'    => $this->pictograms['se142'], // スピーカー
		'14'    => $this->pictograms['se12f'], // ドルマーク
		'15'    => $this->pictograms['se04c'], // 月 1
		'16'    => $this->pictograms['se13d'], // いなずま
		'17'    => '□', // 中四角 1
		'18'    => '■', // 中四角 2
		'19'    => '◇', // 小菱形 1
		'20'    => '◆', // 小菱形 2
		'21'    => '□', // 中四角 1
		'22'    => '■', // 中四角 2
		'23'    => '◇', // 小菱形 1
		'24'    => '◆', // 小菱形 2
		'25'    => $this->pictograms['se026'], // 腕時計
		'26'    => '+', // プラス
		'27'    => '-', // マイナス
		'28'    => $this->pictograms['se32f'], // 星 1
		'29'    => $this->pictograms['se232'], // 上矢印 1
		'30'    => $this->pictograms['se233'], // 下矢印 1
		'31'    => $this->pictograms['se137'], // 丸に斜め線
		'32'    => '▽', // 下三角 1
		'33'    => '△', // 上三角 1
		'34'    => '▼', // 下三角 2
		'35'    => '▲', // 上三角 2
		'36'    => '◇', // 大菱形 1
		'37'    => '◆', // 大菱形 2
		'38'    => '□', // 特大四角 1
		'39'    => '■', // 特大四角 2
		'40'    => '○', // 大丸 1
		'41'    => '●', // 大丸 2
		'42'    => $this->pictograms['se237'], // 上矢印 2 (左上)
		'43'    => $this->pictograms['se238'], // 下矢印 2 (右下)
		'44'    => $this->pictograms['se04a'], // 太陽
		'45'    => $this->pictograms['se016'], // 野球ボール
		'46'    => $this->pictograms['se026'], // 時計
		'47'    => $this->pictograms['se04c'], // 月 2 (顔つき)
		'48'    => $this->pictograms['se325'], // ベル
		'49'    => '[画鋲]', // プッシュピン (画鋲)
		'50'    => $this->pictograms['se002'], // 小顔
		'51'    => $this->pictograms['se022'], // ハート
		'52'    => $this->pictograms['se044'], // マティーニ (カクテルグラス)
		'53'    => $this->pictograms['se110'], // 四つ葉
		'54'    => $this->pictograms['se537'], // トレードマーク (TM)
		'55'    => $this->pictograms['se333'], // かける
		'56'    => $this->pictograms['se301'], // 文書 1
		'57'    => '[砂時計]', // 砂時計 1
		'58'    => '[砂時計]', // 砂時計 2
		'59'    => $this->pictograms['se316'], // フロッピーディスク 1
		'60'    => '*', // 雪の結晶
		'61'    => $this->pictograms['se333'], // バツ 1
		'62'    => $this->pictograms['se333'], // バツ 2
		'63'    => $this->pictograms['se234'], // 右矢印 1
		'64'    => $this->pictograms['se235'], // 左矢印 1
		'65'    => $this->pictograms['se047'], // マグカップ
		'66'    => '÷', // 割る
		'67'    => '[カレンダー]', // カレンダー
		'68'    => $this->pictograms['se056'], // スマイルフェイス
		'69'    => $this->pictograms['se32f'], // 星 2
		'70'    => $this->pictograms['se236'], // 右矢印 2 (右上)
		'71'    => $this->pictograms['se239'], // 左矢印 2 (左下)
		'72'    => $this->pictograms['se034'], // ジュエリー
		'73'    => 'レ', // チェックマーク 1
		'74'    => $this->pictograms['se052'], // 犬 (プードル)
		'75'    => $this->pictograms['se335'], // 星 3
		'76'    => $this->pictograms['se32e'], // スパーク
		'77'    => $this->pictograms['se10f'], // 電球
		'78'    => $this->pictograms['se521'], // 鳥
		'79'    => '[閉フォルダ]', // フォルダ 1 (閉)
		'80'    => $this->pictograms['se001'], // 顔 1
		'81'    => $this->pictograms['se24e'], // コピーライトマーク (C)
		'82'    => $this->pictograms['se24f'], // レジスタードマーク (R)
		'83'    => $this->pictograms['se11e'], // ブリーフケース (ハンドバック)
		'84'    => '[開フォルダ]', // フォルダ 2 (開)
		'85'    => $this->pictograms['se009'], // 電話 1 (プッシュホン)
		'86'    => $this->pictograms['se301'], // 吹き出しコメント
		'87'    => '[クレジットカード]', // クレジットカード
		'88'    => '△', // 上三角 3
		'89'    => '▽', // 下三角 3
		'90'    => $this->pictograms['se50c'], // USA (国旗)
		'91'    => $this->pictograms['se301'], // ノート 3
		'92'    => $this->pictograms['se301'], // クリップボード
		'93'    => $this->pictograms['se045'], // カップ
		'94'    => $this->pictograms['se008'], // カメラ
		'95'    => $this->pictograms['se04b'], // 雨
		'96'    => $this->pictograms['se42b'], // フットボール
		'97'    => $this->pictograms['se148'], // 本 1
		'98'    => $this->pictograms['se137'], // 立ち入り禁止
		'99'    => $this->pictograms['se14e'], // 信号
		'100'   => $this->pictograms['se148'], // 本 2
		'101'   => $this->pictograms['se148'], // 本 3
		'102'   => $this->pictograms['se148'], // 本 4
		'103'   => $this->pictograms['se301'], // 文書 2
		'104'   => $this->pictograms['se313'], // はさみ
		'105'   => $this->pictograms['se301'], // ひめくりカレンダー
		'106'   => $this->pictograms['se125'], // チケット・キップ
		'107'   => $this->pictograms['se049'], // くもり
		'108'   => $this->pictograms['se103'], // 封筒
		'109'   => $this->pictograms['se12f'], // 小切手 (CHECK)
		'110'   => $this->pictograms['se03d'], // ビデオカメラ
		'111'   => $this->pictograms['se507'], // ハンディカム
		'112'   => $this->pictograms['se036'], // 家
		'113'   => $this->pictograms['se304'], // 花 (チューリップ)
		'114'   => '[ナイフ]', // ナイフ
		'115'   => $this->pictograms['se129'], // ビデオテープ
		'116'   => $this->pictograms['se214'], // めがね
		'117'   => '└→', // 回り矢印 1
		'118'   => '←┘', // 回り矢印 2
		'119'   => $this->pictograms['se114'], // むしめがね
		'120'   => $this->pictograms['se03f'], // 鍵
		'121'   => $this->pictograms['se301'], // ノート 1
		'122'   => $this->pictograms['se301'], // ノート 2 (開)
		'123'   => '[ボルトとナット]', // ボルト & ナット
		'124'   => $this->pictograms['se13e'], // くつ (ハイヒール)
		'125'   => $this->pictograms['se15a'], // 車
		'126'   => $this->pictograms['se316'], // フロッピー 2
		'127'   => '[棒グラフ]', // チャート (棒グラフ)
		'128'   => $this->pictograms['se14a'], // グラフ 1 (折れ線グラフ)
		'129'   => $this->pictograms['se101'], // メールボックス
		'130'   => '[懐中電灯]', // 懐中電灯
		'131'   => '[Roldex]', // Roldex
		'132'   => 'レ', // チェックマーク 2
		'133'   => $this->pictograms['se118'], // はっぱ
		'134'   => $this->pictograms['se052'], // 猟犬
		'135'   => '[電池]', // 電池
		'136'   => '[スクロール]', // スクロール
		'137'   => '[画鋲]', // がびょう
		'138'   => $this->pictograms['se144'], // 錠前
		'139'   => $this->pictograms['se12f'], // ドル札
		'140'   => $this->pictograms['se230'], // 指差し確認左
		'141'   => $this->pictograms['se231'], // 指差し確認右
		'142'   => $this->pictograms['se301'], // 台帳
		'143'   => $this->pictograms['se301'], // クリップ
		'144'   => $this->pictograms['se112'], // プレゼント
		'145'   => '[名札]', // 名札
		'146'   => $this->pictograms['se043'], // ゴハン 1 (ナイフとフォーク)
		'147'   => $this->pictograms['se148'], // 複数本
		'148'   => $this->pictograms['se42f'], // トラック
		'149'   => $this->pictograms['se301'], // エンピツ
		'150'   => '[IDO]', // ロゴ (PDC社)
		'151'   => $this->pictograms['se103'], // 封筒 2
		'152'   => $this->pictograms['se116'], // レンチ
		'153'   => $this->pictograms['se102'], // 送信 BOX
		'154'   => $this->pictograms['se101'], // 受信 BOX
		'155'   => $this->pictograms['se009'], // 電話 2 (受話器)
		'156'   => $this->pictograms['se038'], // 工場・建物
		'157'   => '□', // 定規 1 (直線)
		'158'   => '△', // 定規 2 (三角)
		'159'   => $this->pictograms['se14a'], // グラフ 2
		'160'   => '[マンガ肉]', // 食事 2 (マンガ肉)
		'161'   => $this->pictograms['se00a'], // 電話 3 (携帯)
		'162'   => '[コンセント]', // コンセント
		'163'   => $this->pictograms['se428'], // 家族
		'164'   => $this->pictograms['se21a'], // リンク
		'165'   => $this->pictograms['se112'], // パッケージ
		'166'   => $this->pictograms['se00b'], // FAX
		'167'   => $this->pictograms['se04a'] . $this->pictograms['se049'], // ときどき曇り
		'168'   => $this->pictograms['se01d'], // 飛行機
		'169'   => $this->pictograms['se135'], // ボート (船)
		'170'   => '[サイコロ]', // サイコロ
		'171'   => '[新聞]', // 新聞
		'172'   => $this->pictograms['se01e'], // 電車
		'173'   => '　', // 全部ブランク
		'174'   => ' ', // 半分ブランク
		'175'   => ' ', // 4分の1ブランク
		'176'   => $this->pictograms['se30e'], // 喫煙
		'177'   => $this->pictograms['se208'], // 禁煙
		'178'   => $this->pictograms['se20a'], // 車椅子
		'179'   => $this->pictograms['se209'], // 若葉マーク
		'180'   => $this->pictograms['se21c'], // 四角数字 1
		'181'   => $this->pictograms['se21d'], // 四角数字 2
		'182'   => $this->pictograms['se21e'], // 四角数字 3
		'183'   => $this->pictograms['se21f'], // 四角数字 4
		'184'   => $this->pictograms['se220'], // 四角数字 5
		'185'   => $this->pictograms['se221'], // 四角数字 6
		'186'   => $this->pictograms['se222'], // 四角数字 7
		'187'   => $this->pictograms['se223'], // 四角数字 8
		'188'   => $this->pictograms['se224'], // 四角数字 9
		'189'   => $this->pictograms['se225'], // 四角数字 10
		'190'   => $this->pictograms['se443'], // 台風
		'191'   => $this->pictograms['se048'], // ゆきだるま
		'192'   => $this->pictograms['se23f'], // 星座 (おひつじ座)
		'193'   => $this->pictograms['se240'], // 星座 (おうし座)
		'194'   => $this->pictograms['se241'], // 星座 (双子座)
		'195'   => $this->pictograms['se242'], // 星座 (かに座)
		'196'   => $this->pictograms['se243'], // 星座 (しし座)
		'197'   => $this->pictograms['se244'], // 星座 (おとめ座)
		'198'   => $this->pictograms['se245'], // 星座 (天秤座)
		'199'   => $this->pictograms['se246'], // 星座 (さそり座)
		'200'   => $this->pictograms['se247'], // 星座 (いて座)
		'201'   => $this->pictograms['se248'], // 星座 (やぎ座)
		'202'   => $this->pictograms['se249'], // 星座 (水瓶座)
		'203'   => $this->pictograms['se24a'], // 星座 (うお座)
		'204'   => $this->pictograms['se24b'], // 星座 (へびつかい座)
		'205'   => $this->pictograms['se154'], // ATM
		'206'   => $this->pictograms['se156'], // 24 HOURS (コンビニ)
		'207'   => $this->pictograms['se151'], // トイレ
		'208'   => $this->pictograms['se14f'], // パーキング
		'209'   => $this->pictograms['se150'], // バス停
		'210'   => $this->pictograms['se14b'], // アンテナ (位置情報マーク)
		'211'   => $this->pictograms['se202'], // 港 (いかりマーク)
		'212'   => $this->pictograms['se14d'], // 銀行
		'213'   => $this->pictograms['se03a'], // ガススタンド
		'214'   => '[地図]', // 地図
		'215'   => $this->pictograms['se136'], // 自転車
		'216'   => $this->pictograms['se159'], // バス
		'217'   => $this->pictograms['se01f'], // 新幹線
		'218'   => $this->pictograms['se115'], // マラソン
		'219'   => $this->pictograms['se018'], // サッカー
		'220'   => $this->pictograms['se015'], // テニス
		'221'   => $this->pictograms['se013'], // スノーボード
		'222'   => $this->pictograms['se132'], // チェッカーフラッグ (モータースポーツ)
		'223'   => $this->pictograms['se124'], // 遊園地
		'224'   => $this->pictograms['se123'], // 温泉
		'225'   => $this->pictograms['se30b'], // 居酒屋 (赤ちょうちん)
		'226'   => $this->pictograms['se324'], // 映画 (かちんこ)
		'227'   => $this->pictograms['se44b'], // 夜の橋
		'228'   => $this->pictograms['se509'], // 東京タワー
		'229'   => $this->pictograms['se133'], // スロット (777)
		'230'   => $this->pictograms['se312'], // くす玉 (アタリのくす玉)
		'231'   => $this->pictograms['se130'], // 当選弓矢
		'232'   => $this->pictograms['se12b'], // ゲームのコントローラ
		'233'   => $this->pictograms['se12f'], // 賞金
		'234'   => $this->pictograms['se033'], // クリスマスツリー
		'235'   => $this->pictograms['se030'], // 花見 (さくら)
		'236'   => $this->pictograms['se11b'], // お化け
		'237'   => $this->pictograms['se50b'], // 旗 (祝日・日の丸)
		'238'   => $this->pictograms['se348'], // スイカ
		'239'   => $this->pictograms['se046'], // ケーキ
		'240'   => $this->pictograms['se147'], // フライパン (目玉焼き)
		'241'   => '[さくらんぼ]', // さくらんぼ
		'242'   => $this->pictograms['se019'], // ふぐ
		'243'   => $this->pictograms['se347'], // イチゴ
		'244'   => $this->pictograms['se342'], // おにぎり
		'245'   => $this->pictograms['se120'], // ハンバーガー (ファーストフード)
		'246'   => $this->pictograms['se054'], // くじら
		'247'   => $this->pictograms['se52c'], // うさぎ
		'248'   => $this->pictograms['se01a'], // うま
		'249'   => $this->pictograms['se528'], // さる
		'250'   => $this->pictograms['se531'], // かえる
		'251'   => $this->pictograms['se04f'], // 猫
		'252'   => $this->pictograms['se055'], // ペンギン
		'253'   => '[蟻]', // あり
		'254'   => $this->pictograms['se10b'], // ぶた
		'255'   => $this->pictograms['se307'], // やしのき
		'256'   => $this->pictograms['se305'], // ひまわり
		'257'   => $this->pictograms['se056'], // 顔 1 (うれしいカオ)
		'258'   => $this->pictograms['se059'], // 顔 2 (おこったカオ)
		'259'   => $this->pictograms['se057'], // 顔 3 (かなしいカオ)
		'260'   => $this->pictograms['se058'], // 顔 4 (つかれたカオ)
		'261'   => $this->pictograms['se13c'], // 眠い (ZZZ...)
		'262'   => $this->pictograms['se334'], // 怒り (ムカッ)
		'263'   => $this->pictograms['se108'], // 雫 (涙・汗)
		'264'   => $this->pictograms['se105'], // からかう (あっかんべえ)
		'265'   => $this->pictograms['se023'], // ハート 2 (われている)
		'266'   => $this->pictograms['se328'], // ハート 3 (大きい & 小さい)
		'267'   => $this->pictograms['se32e'], // スパーク 2 (キラリマーク)
		'268'   => $this->pictograms['se311'], // 爆弾
		'269'   => $this->pictograms['se11d'], // 炎
		'270'   => '[SOS]', // 捜索 (SOS)
		'271'   => $this->pictograms['se14c'], // 力こぶ
		'272'   => $this->pictograms['se329'], // ハート 5 (矢がささっている)
		'273'   => $this->pictograms['se003'], // キスマーク
		'274'   => $this->pictograms['se10c'], // 宇宙人
		'275'   => $this->pictograms['se443'], // なると
		'276'   => $this->pictograms['se536'], // 足跡 (犬)
		'277'   => $this->pictograms['se11a'], // 悪魔
		'278'   => $this->pictograms['se332'], // 花丸
		'279'   => $this->pictograms['se315'], // 丸秘
		'280'   => '[100点]', // 100点満点
		'281'   => $this->pictograms['se00d'], // パンチ
		'282'   => $this->pictograms['se330'], // ダッシュ
		'283'   => $this->pictograms['se05a'], // ウンチマーク
		'284'   => $this->pictograms['se00f'], // 人差し指サイン
		'285'   => $this->pictograms['se226'], // マル得
		'286'   => $this->pictograms['se11c'], // どくろ
		'287'   => $this->pictograms['se00e'], // おやゆびサイン (指が上)
		'288'   => $this->pictograms['se12a'], // テレビ
		'289'   => $this->pictograms['se03c'], // マイク
		'290'   => '[財布]', // 財布
		'291'   => $this->pictograms['se326'], // メロディ
		'292'   => $this->pictograms['se041'], // ギター (エレキ)
		'293'   => '[バイオリン]', // バイオリン (クラシック)
		'294'   => $this->pictograms['se30a'], // ヘッドフォン
		'295'   => $this->pictograms['se31c'], // 口紅
		'296'   => $this->pictograms['se113'], // アクション (ピストル)
		'297'   => $this->pictograms['se31e'], // エステ
		'298'   =>'[EZ]', // EZ マーク
		'299'   => $this->pictograms['se216'], // 無料 (FREE)
		'300'   => $this->pictograms['se126'], // CD/DVD
		'301'   => $this->pictograms['se319'], // 婦人服
		'302'   => $this->pictograms['se12b'], // UFO
		'303'   => $this->pictograms['se213'], // 更新 (UP!)
		'304'   => $this->pictograms['se13b'], // 注射器 (血)
		'305'   => '[霧]', // 霧
		'306'   => $this->pictograms['se014'], // ゴルフ
		'307'   => $this->pictograms['se42a'], // バスケットボール
		'308'   => '[ページャー]', // ポケットベル
		'309'   => $this->pictograms['se502'], // アート
		'310'   => $this->pictograms['se503'], // 演劇
		'311'   => $this->pictograms['se506'], // イベント (サーカス)
		'312'   => $this->pictograms['se314'], // リボン
		'313'   => $this->pictograms['se34b'], // バースデー
		'314'   => $this->pictograms['se20e'], // スペード
		'315'   => $this->pictograms['se20d'], // ダイヤ
		'316'   => $this->pictograms['se20f'], // クラブ
		'317'   => $this->pictograms['se419'], // 目
		'318'   => $this->pictograms['se41b'], // 耳
		'319'   => $this->pictograms['se011'], // 手 (チョキ)
		'320'   => $this->pictograms['se012'], // 手 (パー)
		'321'   => '●', // 新月
		'322'   => $this->pictograms['se04c'], // やや欠け月
		'323'   => $this->pictograms['se04c'], // 半月
		'324'   => '[CL]', // クリア
		'325'   => $this->pictograms['se225'], // 四角数字 0
		'326'   => $this->pictograms['se24d'], // 決定 (OK)
		'327'   => $this->pictograms['se058'], // ふらふら (顔)
		'328'   => $this->pictograms['se328'], // かわいい
		'329'   => $this->pictograms['se330'], // どんっ (衝撃)
		'330'   => $this->pictograms['se331'], // あせあせ (飛び散る汗)
		'331'   => '[ezplus]', // イージープラス
		'332'   => '[地球]', // 地球
		'333'   => $this->pictograms['se340'], // ラーメン
		'334'   => $this->pictograms['se212'], // NEW
		'335'   => $this->pictograms['se006'], // 紳士服
		'336'   => $this->pictograms['se007'], // 紳士靴
		'337'   => $this->pictograms['se00c'], // パソコン
		'338'   => $this->pictograms['se128'], // ラジオ
		'339'   => $this->pictograms['se032'], // バラ
		'340'   => $this->pictograms['se037'], // チャペル
		'341'   => $this->pictograms['se434'], // 地下鉄
		'342'   => $this->pictograms['se03b'], // 富士山
		'343'   => $this->pictograms['se03e'], // 八分音符
		'344'   => $this->pictograms['se04e'], // 天使
		'345'   => $this->pictograms['se050'], // トラ
		'346'   => $this->pictograms['se051'], // くま
		'347'   => $this->pictograms['se053'], // ねずみ
		'348'   => $this->pictograms['se405'], // ウィンク (顔)
		'349'   => $this->pictograms['se106'], // 目がハート (顔)
		'350'   => $this->pictograms['se107'], // ショッキング (顔)
		'351'   => $this->pictograms['se108'], // 困り (顔)
		'352'   => $this->pictograms['se10a'], // たこ
		'353'   => $this->pictograms['se10d'], // ロケット
		'354'   => $this->pictograms['se10e'], // 王冠
		'355'   => $this->pictograms['se111'], // チュー (キスしている)
		'356'   => $this->pictograms['se116'], // ハンマー
		'357'   => $this->pictograms['se117'], // 打ち上げ花火
		'358'   => $this->pictograms['se118'], // 枯れ葉
		'359'   => $this->pictograms['se11e'], // 仕事かばん
		'360'   => $this->pictograms['se121'], // 噴水
		'361'   => $this->pictograms['se122'], // キャンプ
		'362'   => $this->pictograms['se12d'], // 麻雀
		'363'   => $this->pictograms['se12e'], // VS (バーサス)
		'364'   => $this->pictograms['se131'], // トロフィー
		'365'   => '[亀]', // カメ
		'366'   => $this->pictograms['se511'], // スペイン国旗
		'367'   => $this->pictograms['se512'], // ロシア国旗
		'368'   => $this->pictograms['se137'], // 工事中
		'369'   => $this->pictograms['se13f'], // 風呂
		'370'   => $this->pictograms['se143'], // 祝日マーク
		'371'   => $this->pictograms['se44a'], // 夕方街並み
		'372'   => $this->pictograms['se147'], // 卵割り
		'373'   => $this->pictograms['se14a'], // 株価
		'374'   => $this->pictograms['se152'], // ポリス
		'375'   => $this->pictograms['se153'], // 郵便局
		'376'   => $this->pictograms['se155'], // 病院
		'377'   => $this->pictograms['se157'], // 学校
		'378'   => $this->pictograms['se158'], // ホテル
		'379'   => $this->pictograms['se202'], // 船
		'380'   => $this->pictograms['se207'], // 18禁
		'381'   => $this->pictograms['se20b'], // 圏内
		'382'   => $this->pictograms['se214'], // COOL!
		'383'   => $this->pictograms['se227'], // 割マーク
		'384'   => $this->pictograms['se228'], // ザ・マーク
		'385'   => $this->pictograms['se229'], // IDマーク
		'386'   => $this->pictograms['se22a'], // 満マーク
		'387'   => $this->pictograms['se22b'], // 空マーク
		'388'   => $this->pictograms['se22c'], // 指定マーク
		'389'   => $this->pictograms['se22d'], // 営業中マーク
		'390'   => $this->pictograms['se22e'], // 上指差し
		'391'   => $this->pictograms['se22f'], // 下指差し
		'392'   => '[占い]', // 占い (水晶)
		'393'   => $this->pictograms['se250'], // マナーモード
		'394'   => $this->pictograms['se251'], // 電源OFF
		'395'   => $this->pictograms['se301'], // メモする
		'396'   => $this->pictograms['se302'], // ネクタイ
		'397'   => $this->pictograms['se303'], // ハイビスカス
		'398'   => $this->pictograms['se306'], // 花束
		'399'   => $this->pictograms['se308'], // サボテン
		'400'   => $this->pictograms['se30b'], // お銚子 & 杯
		'401'   => $this->pictograms['se047'], // 乾杯 (ビール)
		'402'   => $this->pictograms['se30d'], // 祝マーク
		'403'   => $this->pictograms['se30f'], // 風邪薬 (カプセル)
		'404'   => $this->pictograms['se310'], // 風船
		'405'   => $this->pictograms['se312'], // クラッカー
		'406'   => '[eznavi]', // eznavigation
		'407'   => $this->pictograms['se318'], // 帽子
		'408'   => $this->pictograms['se31b'], // ロングブーツ
		'409'   => $this->pictograms['se31d'], // ネイル
		'410'   => $this->pictograms['se31f'], // 美容院
		'411'   => $this->pictograms['se320'], // 床屋
		'412'   => $this->pictograms['se321'], // 着物
		'413'   => $this->pictograms['se322'], // ビキニ
		'414'   => $this->pictograms['se20c'], // ハート (トランプ)
		'415'   => $this->pictograms['se327'], // 光るハート
		'416'   => $this->pictograms['se32a'], // 青ハート
		'417'   => $this->pictograms['se32b'], // 緑ハート
		'418'   => $this->pictograms['se32c'], // 黄ハート
		'419'   => $this->pictograms['se32d'], // 紫ハート
		'420'   => $this->pictograms['se32e'], // きらきら
		'421'   => $this->pictograms['se013'], // スキー
		'422'   => $this->pictograms['se332'], // ○
		'423'   => $this->pictograms['se338'], // 日本茶
		'424'   => $this->pictograms['se339'], // 食パン
		'425'   => $this->pictograms['se33a'], // ソフトクリーム
		'426'   => $this->pictograms['se33b'], // ポテト
		'427'   => $this->pictograms['se33c'], // だんご
		'428'   => $this->pictograms['se33d'], // おせんべい
		'429'   => $this->pictograms['se33e'], // ごはん
		'430'   => $this->pictograms['se33f'], // スパゲティ
		'431'   => $this->pictograms['se341'], // カレー
		'432'   => $this->pictograms['se343'], // おでん
		'433'   => $this->pictograms['se344'], // 寿司
		'434'   => $this->pictograms['se345'], // りんご
		'435'   => $this->pictograms['se346'], // みかん
		'436'   => $this->pictograms['se349'], // トマト
		'437'   => $this->pictograms['se34a'], // なす
		'438'   => $this->pictograms['se34c'], // 弁当
		'439'   => $this->pictograms['se34d'], // 鍋
		'440'   => $this->pictograms['se402'], // ふっ (顔)
		'441'   => $this->pictograms['se403'], // しょんぼり (顔)
		'442'   => $this->pictograms['se415'], // 勝ち誇り (顔)
		'443'   => $this->pictograms['se406'], // 失敗 (顔)
		'444'   => $this->pictograms['se407'], // わからん
		'445'   => $this->pictograms['se408'], // 眠い
		'446'   => $this->pictograms['se40a'], // てれてれ (顔)
		'447'   => $this->pictograms['se40b'], // 青ざめ (顔)
		'448'   => $this->pictograms['se40c'], // 風邪ひき
		'449'   => $this->pictograms['se40d'], // 熱 (顔)
		'450'   => $this->pictograms['se40e'], // 横目 (顔)
		'451'   => $this->pictograms['se410'], // びっくり (顔)
		'452'   => $this->pictograms['se40f'], // あせり (顔)
		'453'   => $this->pictograms['se326'], // 楽譜
		'454'   => $this->pictograms['se414'], // にこにこ (顔)
		'455'   => $this->pictograms['se417'], // チュー 2 (顔)
		'456'   => $this->pictograms['se418'], // チュッ (顔)
		'457'   => $this->pictograms['se41a'], // 鼻
		'458'   => $this->pictograms['se41c'], // 口
		'459'   => $this->pictograms['se41d'], // ゴメン／お願い
		'460'   => $this->pictograms['se41f'], // 拍手
		'461'   => $this->pictograms['se420'], // OK! (指で丸サイン)
		'462'   => $this->pictograms['se421'], // ブーイング (指が下)
		'463'   => $this->pictograms['se41e'], // バイバイ
		'464'   => $this->pictograms['se423'], // NG (ネコ)
		'465'   => $this->pictograms['se424'], // OK! 2 (ネコ)
		'466'   => $this->pictograms['se426'], // 平謝り (ネコ)
		'467'   => $this->pictograms['se425'], // カップル
		'468'   => $this->pictograms['se429'], // バニー
		'469'   => $this->pictograms['se042'], // トランペット
		'470'   => $this->pictograms['se42c'], // ビリヤード
		'471'   => $this->pictograms['se42d'], // 水泳
		'472'   => $this->pictograms['se430'], // 消防車
		'473'   => $this->pictograms['se431'], // 救急車
		'474'   => $this->pictograms['se432'], // パトカー
		'475'   => $this->pictograms['se433'], // ジェットコースター
		'476'   => $this->pictograms['se436'], // 門松
		'477'   => $this->pictograms['se438'], // 雛祭り
		'478'   => $this->pictograms['se439'], // 卒業式
		'479'   => $this->pictograms['se43a'], // 入学式
		'480'   => $this->pictograms['se43b'], // こいのぼり
		'481'   => $this->pictograms['se43c'], // 傘
		'482'   => $this->pictograms['se43d'], // 花嫁
		'483'   => $this->pictograms['se43f'], // かき氷
		'484'   => $this->pictograms['se440'], // 線香花火
		'485'   => $this->pictograms['se441'], // 巻き貝
		'486'   => $this->pictograms['se442'], // 風鈴
		'487'   => $this->pictograms['se445'], // ハロウィン
		'488'   => $this->pictograms['se446'], // お月見
		'489'   => $this->pictograms['se448'], // サンタ
		'490'   => $this->pictograms['se44b'], // 夜／流れ星
		'491'   => $this->pictograms['se44c'], // 虹
		'492'   => $this->pictograms['se501'], // ホテル 2
		'493'   => $this->pictograms['se449'], // 日の出
		'494'   => $this->pictograms['se503'], // シルクハット
		'495'   => $this->pictograms['se504'], // デパート
		'496'   => $this->pictograms['se505'], // 城 (日本)
		'497'   => $this->pictograms['se506'], // 城 (ヨーロッパ)
		'498'   => $this->pictograms['se508'], // 工場 2
		'499'   => $this->pictograms['se50d'], // フランス国旗
		'500'   =>'[オープンウェーブ]', // オープンウェーブ
		'501'   => $this->pictograms['se144'], // ロック確認
		'502'   => '[ABC]', // 大文字
		'503'   => '[abc]', // 小文字
		'504'   => '[012]', // 数字
		'505'   => '[,@#]', // 記号
		'506'   => '[可]', // アクセプト
		'507'   => 'レ', // チェックボックス
		'508'   => $this->pictograms['se301'], // エディット
		'509'   => '◎', // ラジオボタン
		'510'   => $this->pictograms['se114'], // 見る (虫眼鏡)
		'511'   => $this->pictograms['se23b'], // 戻る
		'512'   => $this->pictograms['se203'], // お気に入り
		'513'   => $this->pictograms['se104'], // 終了
		'514'   => $this->pictograms['se036'], // ホーム
		'515'   => $this->pictograms['se101'], // 受信箱 1
		'516'   => $this->pictograms['se219'], // マーク
		'517'   => $this->pictograms['se144'], // 個人 (鍵)
		'518'   => '[再読み込み]', // 再読み込み
		'700'   => $this->pictograms['se50e'], // ドイツ国旗
		'701'   => $this->pictograms['se50f'], // イタリア国旗
		'702'   => $this->pictograms['se510'], // イギリス国旗
		'703'   => $this->pictograms['se513'], // 中国国旗
		'704'   => $this->pictograms['se514'], // 韓国国旗
		'705'   => $this->pictograms['se515'], // 白人
		'706'   => $this->pictograms['se516'], // 中国人
		'707'   => $this->pictograms['se517'], // インド人
		'708'   => $this->pictograms['se518'], // おじいさん
		'709'   => $this->pictograms['se519'], // おばあさん
		'710'   => $this->pictograms['se51a'], // 赤ちゃん
		'711'   => $this->pictograms['se51b'], // 工事現場の人
		'712'   => $this->pictograms['se51c'], // お姫様
		'713'   => $this->pictograms['se520'], // イルカ
		'714'   => $this->pictograms['se51f'], // ダンス
		'715'   => $this->pictograms['se522'], // 熱帯魚
		'716'   => $this->pictograms['se525'], // げじげじ
		'717'   => $this->pictograms['se526'], // 象
		'718'   => $this->pictograms['se527'], // コアラ
		'719'   => $this->pictograms['se52b'], // ホルスタイン
		'720'   => $this->pictograms['se52d'], // ヘビ
		'721'   => $this->pictograms['se52e'], // 鶏
		'722'   => $this->pictograms['se52f'], // うりぼう
		'723'   => $this->pictograms['se530'], // ふたこぶらくだ
		'724'   => $this->pictograms['se532'], // A型
		'725'   => $this->pictograms['se533'], // B型
		'726'   => $this->pictograms['se534'], // O型
		'727'   => $this->pictograms['se535'], // AB型
		'728'   => $this->pictograms['se536'], // 足跡
		'729'   => $this->pictograms['se007'], // スニーカー
		'730'   => $this->pictograms['se50b'], // 旗
		'731'   => $this->pictograms['se236'], // 上向きカーブ矢印
		'732'   => $this->pictograms['se238'], // 下向きカーブ矢印
		'733'   => $this->pictograms['se337'] . $this->pictograms['se336'], // 「!?」
		'734'   => $this->pictograms['se337'] . $this->pictograms['se337'], // 「!!」
		'735'   => '-o-', // くるり
		'736'   => '[メロン]', // メロン
		'737'   => '[パイナップル]', // パイナップル
		'738'   => '[葡萄]', // ぶどう
		'739'   => '[バナナ]', // バナナ
		'740'   => '[とうもろこし]', // とうもろこし
		'741'   => '[きのこ]', // きのこ
		'742'   => '[栗]', // 栗
		'743'   => '[桃]', // 桃
		'744'   => '[焼芋]', // やきいも
		'745'   => '[ピザ]', // ピザ
		'746'   => '[ターキー]', // ターキー
		'747'   => '[七夕]', // 七夕笹飾り
		'748'   => $this->pictograms['se045'], // トロピカルドリンク
		'749'   => '[辰]', // 辰
		'750'   => '[ピアノ]', // ピアノ
		'751'   => $this->pictograms['se017'], // サーフィン
		'752'   => $this->pictograms['se019'], // 釣り
		'753'   => '[ボウリング]', // ボウリング
		'754'   => '[なまはげ]', // なまはげ
		'755'   => '[天狗]', // 天狗
		'756'   => '[パンダ]', // パンダ
		'757'   => $this->pictograms['se105'], // あかんべー
		'758'   => $this->pictograms['se10b'], // ぶたの鼻
		'759'   => $this->pictograms['se032'], // 花
		'760'   => $this->pictograms['se33a'], // アイスクリーム
		'761'   => '◎', // ドーナツ
		'762'   => '[クッキー]', // クッキー
		'763'   => $this->pictograms['se437'], // チョコ
		'764'   => '[キャンディ]', // キャンディ (包み)
		'765'   => '[ぺろぺろキャンディ]',// キャンディ (ぺろぺろ)
		'766'   => '(/_＼)', // 見ざる (猿)
		'767'   => '(・x・)', // 言わざる (猿)
		'768'   => '|(・_・)|', // 聞かざる (猿)
		'769'   => $this->pictograms['se03b'], // 火山
		'770'   => $this->pictograms['se314'] . $this->pictograms['se022'], // リボンがけのハート
		'771'   => '[ABC]', // 英語「ABC」
		'772'   => '[プリン]', // プリン
		'773'   => '[蜜蜂]', // ミツバチ
		'774'   => '[てんとう虫]', // テントウムシ
		'775'   => '[蜂蜜ポット]', // 蜂蜜ポット
		'776'   => $this->pictograms['se345'], // 青りんご
		'777'   => $this->pictograms['se04e'], // 羽のはえたお札
		'778'   => $this->pictograms['se407'], // 目がまわる時の記号
		'779'   => $this->pictograms['se416'], // ぷー (かわいく怒)
		'780'   => $this->pictograms['se416'], // ぷー (かわいく怒) (ネコ)
		'781'   => $this->pictograms['se44b'], // 天の川
		'782'   => $this->pictograms['se417'], // チュー (ネコ)
		'783'   => $this->pictograms['se414'], // にこ (ネコ)
		'784'   => $this->pictograms['se103'], // メールする
		'785'   => $this->pictograms['se412'], // 泣き笑い (ネコ)
		'786'   => $this->pictograms['se412'], // 泣き笑い (顔)
		'787'   => $this->pictograms['se106'], // 目がハート (ネコ)
		'788'   => $this->pictograms['se410'], // ほえー (ネコ)
		'789'   => $this->pictograms['se410'], // ほえー (顔)
		'790'   => $this->pictograms['se413'], // 涙ぽろり (ネコ)
		'791'   => $this->pictograms['se413'], // 涙ぽろり (顔)
		'792'   => $this->pictograms['se402'], // きりり (ネコ)
		'793'   => $this->pictograms['se319'], // ドレス
		'794'   => '[モヤイ像]', // モヤイ像
		'795'   => $this->pictograms['se039'], // 駅
		'796'   => '[花札]', // 花札
		'797'   => $this->pictograms['se519'], // ジョーカー
		'798'   => '[海老フライ]', // エビフライ
		'799'   => $this->pictograms['se101'], // eメールアイコン
		'800'   => $this->pictograms['se201'], // 歩く人
		'801'   => $this->pictograms['se432'], // パトカーのランプ
		'802'   => $this->pictograms['se03d'], // ezmovie
		'803'   => $this->pictograms['se328'], // ドキドキしているハート
		'804'   => $this->pictograms['se523'], // 正面向きのひよこ
		'805'   => '¶', // ジーンズ
		'806'   => $this->pictograms['se329'], // ハートつきメール
		'807'   => '[循環矢印]', // 循環矢印
		'808'   => '⇔', // 左右両方矢印
		'809'   => '↑↓', // 上下両方矢印
		'810'   => $this->pictograms['se43e'], // 荒波
		'811'   => $this->pictograms['se447'], // 双葉
		'812'   => $this->pictograms['se441'], // かたつむり
		'813'   => $this->pictograms['se415'], // うっしっし (ネコ)
		'814'   => $this->pictograms['se415'], // うっしっし (顔)
		'815'   => $this->pictograms['se101'], // Cメールアイコン
		'816'   => $this->pictograms['se447'], // ハーブ
		'817'   => $this->pictograms['se010'], // 手 (グー)
		'818'   => $this->pictograms['se210'], // 「#」
		'819'   => $this->pictograms['se012'], // 挙手 (キャラクター)
		'820'   => $this->pictograms['se422'], // 万歳 (キャラクター)
		'821'   => $this->pictograms['se403'], // しょんぼり (キャラクター)
		'822'   => $this->pictograms['se416'], // かわいく怒る (キャラクター)
		'd001'  => $this->pictograms['se04a'], // 晴れ
		'd002'  => $this->pictograms['se049'], // 曇り
		'd003'  => $this->pictograms['se04b'], // 雨
		'd004'  => $this->pictograms['se048'], // 雪 
		'd005'  => $this->pictograms['se13d'], // 雷
		'd006'  => $this->pictograms['se443'], // 台風
		'd007'  => '[霧]', // 霧
		'd008'  => $this->pictograms['se43c'], // 小雨
		'd009'  => $this->pictograms['se23f'], // 牡羊座
		'd010'  => $this->pictograms['se240'], // 牡牛座
		'd011'  => $this->pictograms['se241'], // 双子座
		'd012'  => $this->pictograms['se242'], // 蟹座
		'd013'  => $this->pictograms['se243'], // 獅子座
		'd014'  => $this->pictograms['se244'], // 乙女座
		'd015'  => $this->pictograms['se245'], // 天秤座
		'd016'  => $this->pictograms['se246'], // 蠍座
		'd017'  => $this->pictograms['se247'], // 射手座
		'd018'  => $this->pictograms['se248'], // 山羊座
		'd019'  => $this->pictograms['se249'], // 水瓶座
		'd020'  => $this->pictograms['se24a'], // 魚座
		'd021'  => $this->pictograms['se322'], // スポーツ
		'd022'  => $this->pictograms['se016'], // 野球
		'd023'  => $this->pictograms['se014'], // ゴルフ
		'd024'  => $this->pictograms['se015'], // テニス
		'd025'  => $this->pictograms['se018'], // サッカー
		'd026'  => $this->pictograms['se013'], // スキー
		'd027'  => $this->pictograms['se42a'], // バスケットボール
		'd028'  => $this->pictograms['se132'], // モータースポーツ (チェッカーフラッグ)
		'd029'  => '[ページャー]', // ポケットベル
		'd030'  => $this->pictograms['se01e'], // 電車
		'd031'  => $this->pictograms['se434'], // 地下鉄
		'd032'  => $this->pictograms['se435'], // 新幹線
		'd033'  => $this->pictograms['se01b'], // 車 (セダン)
		'd034'  => $this->pictograms['se42e'], // 車 (RV)
		'd035'  => $this->pictograms['se159'], // バス
		'd036'  => $this->pictograms['se202'], // 船
		'd037'  => $this->pictograms['se01d'], // 飛行機
		'd038'  => $this->pictograms['se036'], // 家
		'd039'  => $this->pictograms['se038'], // ビル
		'd040'  => $this->pictograms['se153'], // 郵便局
		'd041'  => $this->pictograms['se155'], // 病院
		'd042'  => $this->pictograms['se14d'], // 銀行
		'd043'  => $this->pictograms['se154'], // ATM
		'd044'  => $this->pictograms['se158'], // ホテル
		'd045'  => $this->pictograms['se156'], // コンビニ
		'd046'  => $this->pictograms['se03a'], // ガソリンスタンド
		'd047'  => $this->pictograms['se14f'], // 駐車場
		'd048'  => $this->pictograms['se14e'], // 信号
		'd049'  => $this->pictograms['se151'], // トイレ
		'd050'  => $this->pictograms['se043'], // レストラン
		'd051'  => $this->pictograms['se045'], // 喫茶店
		'd052'  => $this->pictograms['se044'], // バー (マティーニ)
		'd053'  => $this->pictograms['se047'], // ビール
		'd054'  => $this->pictograms['se120'], // ファーストフード (ハンバーガー)
		'd055'  => $this->pictograms['se13e'], // ブティック
		'd056'  => $this->pictograms['se313'], // 美容院 (鋏)
		'd057'  => $this->pictograms['se03c'], // カラオケ
		'd058'  => $this->pictograms['se03d'], // 映画
		'd059'  => $this->pictograms['se236'], // 右斜め上
		'd060'  => $this->pictograms['se124'], // 遊園地 (木馬)
		'd061'  => $this->pictograms['se30a'], // 音楽 (ヘッドホン)
		'd062'  => $this->pictograms['se502'], // アート
		'd063'  => $this->pictograms['se503'], // 演劇
		'd064'  => $this->pictograms['se506'], // イベント (サーカス)
		'd065'  => $this->pictograms['se125'], // チケット
		'd066'  => $this->pictograms['se30e'], // 喫煙
		'd067'  => $this->pictograms['se208'], // 禁煙
		'd068'  => $this->pictograms['se008'], // カメラ
		'd069'  => $this->pictograms['se323'], // カバン
		'd070'  => $this->pictograms['se148'], // 本
		'd071'  => $this->pictograms['se314'], // リボン
		'd072'  => $this->pictograms['se112'], // プレゼント
		'd073'  => $this->pictograms['se34b'], // バースデー
		'd074'  => $this->pictograms['se009'], // 電話
		'd075'  => $this->pictograms['se00a'], // 携帯電話
		'd076'  => $this->pictograms['se301'], // メモ
		'd077'  => $this->pictograms['se12a'], // TV
		'd078'  => $this->pictograms['se12b'], // ゲーム
		'd079'  => $this->pictograms['se126'], // CD
		'd080'  => $this->pictograms['se20c'], // ハート
		'd081'  => $this->pictograms['se20e'], // スペード
		'd082'  => $this->pictograms['se20d'], // ダイヤ
		'd083'  => $this->pictograms['se20f'], // クラブ
		'd084'  => $this->pictograms['se419'], // 目
		'd085'  => $this->pictograms['se41b'], // 耳
		'd086'  => $this->pictograms['se010'], // 手 (グー)
		'd087'  => $this->pictograms['se011'], // 手 (チョキ)
		'd088'  => $this->pictograms['se012'], // 手 (パー)
		'd089'  => $this->pictograms['se238'], // 右斜め下
		'd090'  => $this->pictograms['se237'], // 左斜め上
		'd091'  => $this->pictograms['se536'], // 足
		'd092'  => $this->pictograms['se007'], // くつ
		'd093'  => $this->pictograms['se214'], // 眼鏡
		'd094'  => $this->pictograms['se20a'], // 車椅子
		'd095'  => '●', // 新月
		'd096'  => $this->pictograms['se04c'], // やや欠け月
		'd097'  => $this->pictograms['se04c'], // 半月
		'd098'  => $this->pictograms['se04c'], // 三日月
		'd099'  => '○', // 満月
		'd100'  => $this->pictograms['se052'], // 犬
		'd101'  => $this->pictograms['se04f'], // 猫
		'd102'  => $this->pictograms['se01c'], // リゾート (ヨット)
		'd103'  => $this->pictograms['se033'], // クリスマス
		'd104'  => $this->pictograms['se239'], // 左斜め下
		'd105'  => $this->pictograms['se104'], // phone to
		'd106'  => $this->pictograms['se103'], // mail to
		'd107'  => $this->pictograms['se00b'], // fax to
		'd108'  => '[i]', // iモード
		'd109'  => '[i]', // iモード (枠付き)
		'd110'  => $this->pictograms['se103'], // メール
		'd111'  => '[ドコモ提供]', // ドコモ提供
		'd112'  => '[D]', // ドコモポイント
		'd113'  => $this->pictograms['se215'], // 有料
		'd114'  => $this->pictograms['se216'], // 無料
		'd115'  => $this->pictograms['se229'], // ID
		'd116'  => $this->pictograms['se03f'], // パスワード
		'd117'  => '←┘', // 次項有
		'd118'  => '[CL]', // クリア
		'd119'  => $this->pictograms['se114'], // サーチ (調べる)
		'd120'  => $this->pictograms['se212'], // NEW
		'd121'  => $this->pictograms['se14b'], // 位置情報
		'd122'  => $this->pictograms['se211'], // フリーダイヤル
		'd123'  => $this->pictograms['se210'], // シャープダイヤル
		'd124'  => 'Q', // モバQ
		'd125'  => $this->pictograms['se21c'], // 1 (one)
		'd126'  => $this->pictograms['se21d'], // 2 (two)
		'd127'  => $this->pictograms['se21e'], // 3 (three)
		'd128'  => $this->pictograms['se21f'], // 4 (four)
		'd129'  => $this->pictograms['se220'], // 5 (five)
		'd130'  => $this->pictograms['se221'], // 6 (six)
		'd131'  => $this->pictograms['se222'], // 7 (seven)
		'd132'  => $this->pictograms['se223'], // 8 (eight)
		'd133'  => $this->pictograms['se224'], // 9 (nine)
		'd134'  => $this->pictograms['se225'], // 0 (zero)
		'd135'  => $this->pictograms['se24d'], // 決定 (OK)
		'd136'  => $this->pictograms['se022'], // 黒ハート
		'd137'  => $this->pictograms['se328'], // 揺れるハート
		'd138'  => $this->pictograms['se023'], // 失恋
		'd139'  => $this->pictograms['se328'], // ハートたち (複数ハート)
		'd140'  => $this->pictograms['se056'], // わーい (嬉しい顔)
		'd141'  => $this->pictograms['se059'], // ちっ (怒った顔)
		'd142'  => $this->pictograms['se057'], // がく～ (落胆した顔)
		'd143'  => $this->pictograms['se407'], // もうやだ～ (悲しい顔)
		'd144'  => $this->pictograms['se406'], // ふらふら
		'd145'  => $this->pictograms['se236'], // グッド (上向き矢印)
		'd146'  => $this->pictograms['se03e'], // るんるん (音符)
		'd147'  => $this->pictograms['se123'], // いい気分 (温泉)
		'd148'  => $this->pictograms['se204'], // かわいい
		'd149'  => $this->pictograms['se003'], // キスマーク
		'd150'  => $this->pictograms['se32e'], // ぴかぴか (新しい)
		'd151'  => $this->pictograms['se10f'], // ひらめき
		'd152'  => $this->pictograms['se334'], // むかっ (怒り)
		'd153'  => $this->pictograms['se00d'], // パンチ
		'd154'  => $this->pictograms['se311'], // 爆弾
		'd155'  => $this->pictograms['se326'], // ムード
		'd156'  => $this->pictograms['se238'], // バッド (下向き矢印)
		'd157'  => $this->pictograms['se13c'], // 眠い (睡眠)
		'd158'  => $this->pictograms['se021'], // exclamation
		'd159'  => $this->pictograms['se021'] . $this->pictograms['se020'], // exclamation and question
		'd160'  => $this->pictograms['se021'], // double exclamation
		'd161'  => $this->pictograms['se330'], // どんっ (衝撃)
		'd162'  => $this->pictograms['se331'], // あせあせ (飛び散る汗)
		'd163'  => $this->pictograms['se108'], // たらーっ (汗)
		'd164'  => $this->pictograms['se330'], // ダッシュ (走り出すさま)
		'd165'  => '～～', // ー (長音記号1)
		'd166'  => '-o-', // ー (長音記号2)
		'd167'  => $this->pictograms['se324'], // カチンコ
		'd168'  => $this->pictograms['se12f'], // ふくろ
		'd169'  => $this->pictograms['se301'], // ペン
		'd170'  => $this->pictograms['se056'], // 人影
		'd171'  => $this->pictograms['se11f'], // いす
		'd172'  => $this->pictograms['se44b'], // 夜
		'd173'  => '→SOON', // soon
		'd174'  => '←ON→', // on
		'd175'  => 'END←', // end
		'd176'  => $this->pictograms['se026'], // 時計
		'd201'  => 'α', // iアプリ
		'd202'  => '[α]', // iアプリ (枠付き)
		'd203'  => $this->pictograms['se006'], // Tシャツ (ボーダー)
		'd204'  => '[財布]', // がま口財布
		'd205'  => $this->pictograms['se31c'], // 化粧
		'd206'  => '¶', // ジーンズ
		'd207'  => $this->pictograms['se013'], // スノボ
		'd208'  => $this->pictograms['se325'], // チャペル
		'd209'  => '[ドア]', // ドア
		'd210'  => $this->pictograms['se12f'], // ドル袋
		'd211'  => $this->pictograms['se00c'], // パソコン
		'd212'  => $this->pictograms['se101'] . $this->pictograms['se022'], // ラブレター
		'd213'  => $this->pictograms['se116'], // レンチ
		'd214'  => $this->pictograms['se301'], // 鉛筆
		'd215'  => $this->pictograms['se10e'], // 王冠
		'd216'  => $this->pictograms['se034'], // 指輪
		'd217'  => '[砂時計]', // 砂時計
		'd218'  => $this->pictograms['se136'], // 自転車
		'd219'  => $this->pictograms['se338'], // 湯のみ
		'd220'  => $this->pictograms['se026'], // 腕時計
		'd221'  => $this->pictograms['se403'], // 考えてる顔
		'd222'  => $this->pictograms['se40a'], // ほっとした顔
		'd223'  => $this->pictograms['se415'] . $this->pictograms['se331'], // 冷や汗 (顔)
		'd224'  => $this->pictograms['se108'], // 冷や汗2 (顔)
		'd225'  => $this->pictograms['se416'], // ぷっくっくな顔
		'd226'  => $this->pictograms['se40e'], // ボケーっとした顔
		'd227'  => $this->pictograms['se106'], // 目がハート (顔)
		'd228'  => $this->pictograms['se00e'], // 指でOK
		'd229'  => $this->pictograms['se105'], // あっかんべー
		'd230'  => $this->pictograms['se405'], // ウィンク
		'd231'  => $this->pictograms['se40a'], // うれしい顔
		'd232'  => $this->pictograms['se406'], // がまん顔
		'd233'  => $this->pictograms['se402'], // 猫2
		'd234'  => $this->pictograms['se411'], // 泣き顔
		'd235'  => $this->pictograms['se413'], // 涙
		'd236'  => $this->pictograms['se423'], // NG
		'd237'  => $this->pictograms['se301'], // クリップ
		'd238'  => $this->pictograms['se24e'], // コピーライト (C)
		'd239'  => $this->pictograms['se537'], // トレードマーク (TM)
		'd240'  => $this->pictograms['se115'], // 走る人
		'd241'  => $this->pictograms['se315'], // マル秘
		'd242'  => '[リサイクル]', // リサイクル
		'd243'  => $this->pictograms['se24f'], // レジスタードトレードマーク (R)
		'd244'  => $this->pictograms['se252'], // 危険・警告 (!)
		'd245'  => '[禁]', // 禁止
		'd246'  => $this->pictograms['se22b'], // 空室・空席・空車
		'd247'  => '[合格]', // 合格マーク
		'd248'  => $this->pictograms['se22a'], // 満室・満席・満車
		'd249'  => '⇔', // 矢印左右
		'd250'  => '↑↓', // 矢印上下
		'd251'  => $this->pictograms['se157'], // 学校
		'd252'  => $this->pictograms['se43e'], // 波
		'd253'  => $this->pictograms['se03b'], // 富士山
		'd254'  => $this->pictograms['se110'], // クローバー
		'd255'  => '[さくらんぼ]', // さくらんぼ
		'd256'  => $this->pictograms['se304'], // チューリップ
		'd257'  => '[バナナ]', // バナナ
		'd258'  => $this->pictograms['se345'], // りんご
		'd259'  => $this->pictograms['se110'], // 芽
		'd260'  => $this->pictograms['se118'], // もみじ
		'd261'  => $this->pictograms['se030'], // 桜
		'd262'  => $this->pictograms['se342'], // おにぎり
		'd263'  => $this->pictograms['se046'], // ショートケーキ
		'd264'  => $this->pictograms['se30b'], // とっくり (おちょこ付き)
		'd265'  => $this->pictograms['se340'], // どんぶり
		'd266'  => $this->pictograms['se339'], // パン
		'd267'  => $this->pictograms['se441'], // かたつむり
		'd268'  => $this->pictograms['se523'], // ひよこ
		'd269'  => $this->pictograms['se055'], // ペンギン
		'd270'  => $this->pictograms['se019'], // 魚
		'd271'  => $this->pictograms['se056'], // うまい! (顔)
		'd272'  => $this->pictograms['se415'], // ウッシッシ (顔)
		'd273'  => $this->pictograms['se01a'], // ウマ
		'd274'  => $this->pictograms['se10b'], // ブタ
		'd275'  => $this->pictograms['se044'], // ワイングラス
		'd276'  => $this->pictograms['se107'], // げっそり (顔)
		'e253'  => $this->pictograms['se00f'], // 人差し指
		'e254'  => $this->pictograms['se425'], // カップル
		'e255'  => $this->pictograms['se209'], // 若葉マーク
		'e256'  => $this->pictograms['se041'], // ギター
		'e257'  => $this->pictograms['se14a'], // 株価チャート
		'e258'  => $this->pictograms['se207'], // 18歳未満禁止
		'e259'  => $this->pictograms['se12d'], // 麻雀牌
		'e260'  => $this->pictograms['se428'], // コミュニティ
		'e261'  => '[HIT]', // ヒット
		'e262'  => '[新聞]', // 新聞
		'e263'  => $this->pictograms['se448'], // サンタクロース
		'e264'  => $this->pictograms['se428'], // 家族
		'e265'  => '　', // [未使用]
		'e266'  => '●', // コイン
		'e267'  => '　', // [未使用]
		'e268'  => '　', // [未使用]
		'e269'  => 'EM', // EMOBILE ロゴ (白地)
		'e270'  => 'EM', // EMOBILE ロゴ (赤地)
		'e271'  => '　', // [未使用]
		'e272'  => '　', // [未使用]
		'e273'  => '　', // [未使用]
		'e274'  => '　', // [未使用]
		'e275'  => '　', // [未使用]
		'e276'  => '　', // [未使用]
		'e277'  => '　', // [未使用]
		'e278'  => '　', // [未使用]
		'wf040' => $this->pictograms['se022'], // ハート
		'wf041' => $this->pictograms['se026'], // 時計
		'wf042' => $this->pictograms['se009'], // 電話
		'wf043' => $this->pictograms['se045'], // カップ
		'wf044' => '*', // *
		'wf045' => '↑↓', // 上下 (矢印)
		'wf046' => '⇔', // 左右 (矢印)
		'wf047' => '(((', // 電波 (左)
		'wf048' => $this->pictograms['se04a'], // 晴れ
		'wf049' => $this->pictograms['se04b'], // 雨
		'wf04a' => $this->pictograms['se049'], // 曇り
		'wf04b' => $this->pictograms['se108'], // 涙
		'wf04c' => $this->pictograms['se056'], // 笑顔
		'wf04d' => $this->pictograms['se003'], // 口 (キスマーク)
		'wf04e' => $this->pictograms['se03e'], // メロディ (十六分音符)
		'wf04f' => $this->pictograms['se01b'], // 車
		'wf050' => $this->pictograms['se01e'], // 電車
		'wf051' => $this->pictograms['se01d'], // 飛行機
		'wf052' => '[バイク]'          , // バイク
		'wf053' => $this->pictograms['se036'], // 家
		'wf054' => $this->pictograms['se038'], // ビル
		'wf055' => $this->pictograms['se011'], // ピース (手)
		'wf056' => $this->pictograms['se043'], // ディナー (ナイフとフォーク)レストラン)
		'wf057' => $this->pictograms['se044'], // グラスル)
		'wf058' => $this->pictograms['se413'], // 泣く (顔)
		'wf059' => $this->pictograms['se304'], // チューリップ
		'wf05a' => $this->pictograms['se016'], // 野球 (バット)
		'wf05b' => $this->pictograms['se016'], // ボール
		'wf05c' => $this->pictograms['se010'], // パンチ (手)
		'wf05d' => $this->pictograms['se13d'], // 雷
		'wf05e' => $this->pictograms['se059'], // 怒った顔
		'wf05f' => $this->pictograms['se047'], // ビール
		'wf060' => $this->pictograms['se301'], // ノート
		'wf061' => $this->pictograms['se301'], // ペン (鉛筆)
		'wf062' => $this->pictograms['se11c'], // ドクロ
		'wf063' => $this->pictograms['se101'], // メール
		'wf064' => $this->pictograms['se208'], // 禁煙
		'wf065' => $this->pictograms['se325'], // ベル
		'wf066' => $this->pictograms['se030'], // 花
		'wf067' => $this->pictograms['se123'], // 温泉
		'wf068' => $this->pictograms['se04c'], // 月 (26日目)
		'wf069' => $this->pictograms['se50b'], // 旗
		'wf06a' => $this->pictograms['se40c'], // マスク (顔)
		'wf06b' => $this->pictograms['se30a'], // レコード
		'wf06c' => '[肉]', // 肉
		'wf06d' => $this->pictograms['se052'], // 犬
		'wf06e' => $this->pictograms['se04f'], // 猫
		'wf06f' => $this->pictograms['se109'], // 猿
		'wf070' => $this->pictograms['se526'], // 象
		'wf071' => $this->pictograms['se10a'], // たこ
		'wf072' => $this->pictograms['se340'], // ヌードル
		'wf073' => $this->pictograms['se03c'], // マイク (カラオケ)
		'wf074' => $this->pictograms['se334'], // むかっ (怒り)
		'wf075' => $this->pictograms['se523'], // ひよこ
		'wf076' => $this->pictograms['se408'], // 眠り顔
		'wf077' => $this->pictograms['se045'], // コーヒー
		'wf078' => $this->pictograms['se30e'], // タバコ
		'wf079' => $this->pictograms['se331'], // 汗
		'wf07a' => $this->pictograms['se342'], // おにぎり
		'wf07b' => $this->pictograms['se323'], // カバン
		'wf07c' => $this->pictograms['se05a'], // うんち
		'wf07d' => $this->pictograms['se302'], // ネクタイ
		'wf07e' => $this->pictograms['se006'], // シャツ
		'wf080' => $this->pictograms['se348'], // すいか
		'wf081' => $this->pictograms['se43f'], // カキ氷
		'wf082' => $this->pictograms['se322'], // ビキニ
		'wf083' => $this->pictograms['se313'], // はさみ
		'wf084' => $this->pictograms['se13b'], // 注射
		'wf085' => $this->pictograms['se202'], // 船 (錨)
		'wf086' => $this->pictograms['se531'], // かえる
		'wf087' => $this->pictograms['se012'], // バイバイ (手)
		'wf088' => $this->pictograms['se023'], // 失恋
		'wf089' => $this->pictograms['se20d'], // ダイヤ (トランプ)ンプ)
		'wf08a' => $this->pictograms['se20f'], // クローバー (トランプ)
		'wf08b' => $this->pictograms['se20e'], // スペード (トランプ))
		'wf08c' => $this->pictograms['se301'], // クリップ
		'wf08d' => $this->pictograms['se048'], // 雪だるま
		'wf08e' => $this->pictograms['se34b'], // ケーキ
		'wf08f' => $this->pictograms['se345'], // りんご
		'wf090' => $this->pictograms['se112'], // プレゼント
		'wf091' => $this->pictograms['se12f'], // お金 (ドル)
		'wf092' => '[EXIT]', // 出口
		'wf093' => '[ドア]', // 入り口
		'wf094' => $this->pictograms['se518'], // おやじ
		'wf095' => $this->pictograms['se00a'], // PHS
		'wf096' => $this->pictograms['se32f'], // 星
		'wf097' => $this->pictograms['se125'], // チケット
		'wf098' => $this->pictograms['se328'], // 複数ハート
		'wf099' => $this->pictograms['se10f'], // ひらめき
		'wf09a' => $this->pictograms['se536'], // 足跡
		'wf09b' => $this->pictograms['se057'], // 笑顔
		'wf09c' => $this->pictograms['se015'], // テニス
		'wf09d' => $this->pictograms['se03d'], // 映画
		'wf09e' => $this->pictograms['se013'], // スキー
		'wf09f' => $this->pictograms['se337'].$this->pictograms['se337'], // !!
		'wf0a0' => $this->pictograms['se337'].$this->pictograms['se336'], // !?
		'wf0a1' => $this->pictograms['se336'], // ?
		'wf0a2' => $this->pictograms['se238'], // 下降 (矢印)
		'wf0a3' => $this->pictograms['se236'], // 上昇 (矢印)
		'wf0a4' => $this->pictograms['se00e'], // グッド (親指)
		'wf0a5' => $this->pictograms['se14c'], // 力こぶ
		'wf0a6' => $this->pictograms['se329'], // キューピット (ハートと矢)
		'wf0a7' => $this->pictograms['se332'], // うずまき
		'wf0a8' => $this->pictograms['se443'], // 台風
		'wf0a9' => $this->pictograms['se43e'], // 海
		'wf0aa' => $this->pictograms['se017'], // サーフィン
		'wf0ab' => $this->pictograms['se04d'], // 山
		'wf0ac' => $this->pictograms['se03b'], // 富士山
		'wf0ad' => $this->pictograms['se122'], // キャンプ
		'wf0ae' => $this->pictograms['se119'], // 落ち葉
		'wf0af' => $this->pictograms['se159'], // バス
		'wf0b0' => $this->pictograms['se018'], // サッカー
		'wf0b1' => $this->pictograms['se209'], // 初心者
		'wf0b2' => $this->pictograms['se23d'], // 巻き戻し
		'wf0b3' => $this->pictograms['se23c'], // 早送り
		'wf0b4' => '[重要]', // 重要
		'wf0b5' => $this->pictograms['se207'], // 18禁
		'wf0b6' => $this->pictograms['se252'], // 注意
		'wf0b7' => '[リサイクル]', // リサイクル
		'wf0b8' => $this->pictograms['se20b'], // 電界強度
		'wf0b9' => ')))', // 電波 (右)
		'wf0ba' => $this->pictograms['se333'], // バツ
		'wf0bb' => $this->pictograms['se24e'], // コピーライト
		'wf0bc' => $this->pictograms['se24f'], // レジスタードトレードマーク
		'wf0bd' => $this->pictograms['se133'], // スリーセブン
		'wf0be' => $this->pictograms['se225'], // 0 (zero)
		'wf0bf' => $this->pictograms['se21c'], // 1 (one)
		'wf0c0' => $this->pictograms['se21d'], // 2 (two)
		'wf0c1' => $this->pictograms['se21e'], // 3 (three)
		'wf0c2' => $this->pictograms['se21f'], // 4 (four)
		'wf0c3' => $this->pictograms['se220'], // 5 (five)
		'wf0c4' => $this->pictograms['se221'], // 6 (six)
		'wf0c5' => $this->pictograms['se222'], // 7 (seven)
		'wf0c6' => $this->pictograms['se223'], // 8 (eight)
		'wf0c7' => $this->pictograms['se224'], // 9 (nine)
		'wf0c8' => $this->pictograms['se23f'], // 牡羊座
		'wf0c9' => $this->pictograms['se240'], // 牡牛座
		'wf0ca' => $this->pictograms['se241'], // 双子座
		'wf0cb' => $this->pictograms['se242'], // 蟹座
		'wf0cc' => $this->pictograms['se243'], // 獅子座
		'wf0cd' => $this->pictograms['se244'], // 乙女座
		'wf0ce' => $this->pictograms['se245'], // 天秤座
		'wf0cf' => $this->pictograms['se246'], // 蠍座
		'wf0d0' => $this->pictograms['se24b'], // へびつかい座
		'wf0d1' => $this->pictograms['se247'], // 射手座
		'wf0d2' => $this->pictograms['se248'], // 山羊座
		'wf0d3' => $this->pictograms['se249'], // 水瓶座
		'wf0d4' => $this->pictograms['se24a'], // 魚座
		'wf0d5' => '[地蔵]', // 地蔵
		'wf0d6' => $this->pictograms['se120'], // マクドナルド
		'wf0d7' => $this->pictograms['se120'], // モスバーガー
		'wf0d8' => '　', // [未使用]
		'wf0d9' => $this->pictograms['se120'], // ロッテリア
		'wf0da' => '　', // [未使用]
		'wf0db' => $this->pictograms['se045'], // ドトールコーヒー
		'wf0dc' => '　', // [未使用]
		'wf0dd' => '　', // [未使用]
		'wf0de' => '　', // [未使用]
		'wf0df' => '　', // [未使用]
		'wf0e0' => $this->pictograms['se043'], // もも (バーミヤン?)
		'wf0e1' => '　', // [未使用]
		'wf0e2' => '　', // [未使用]
		'wf0e3' => $this->pictograms['se043'], // びっくりドンキー
		'wf0e4' => '　', // [未使用]
		'wf0e5' => '　', // [未使用]
		'wf0e6' => '　', // [未使用]
		'wf0e7' => $this->pictograms['se156'], // ローソン
		'wf0e8' => '　', // [未使用]
		'wf0e9' => $this->pictograms['se156'], // am/pm
		'wf0ea' => '　', // [未使用]
		'wf0eb' => '　', // [未使用]
		'wf0ec' => '　', // [未使用]
		'wf0ed' => '　', // [未使用]
		'wf0ee' => '　', // [未使用]
		'wf0ef' => '　', // [未使用]
		'wf0f0' => $this->pictograms['se504'], // 西武
		'wf0f1' => '　', // [未使用]
		'wf0f2' => '　', // [未使用]
		'wf0f3' => '　', // [未使用]
		'wf0f4' => '　', // [未使用]
		'wf0f5' => '　', // [未使用]
		'wf0f6' => '　', // [未使用]
		'wf0f7' => '　', // [未使用]
		'wf0f8' => '　', // [未使用]
		'wf0f9' => '　', // [未使用]
		'wf0fa' => '　', // [未使用]
		'wf0fb' => '　', // [未使用]
		'wf0fc' => $this->pictograms['se052'], // ハチ公
		'wf140' => '[モヤイ像]', // モヤイ
		'wf141' => '　', // [未使用]
		'wf142' => '　', // [未使用]
		'wf143' => '　', // [未使用]
		'wf144' => '　', // [未使用]
		'wf145' => '　', // [未使用]
		'wf146' => '　', // [未使用]
		'wf147' => '　', // [未使用]
		'wf148' => $this->pictograms['se14d'], // UFJ
		'wf149' => '　', // [未使用]
		'wf14a' => '　', // [未使用]
		'wf14b' => '　', // [未使用]
		'wf14c' => '　', // [未使用]
		'wf14d' => '[EXIT]', // 非常口
		'wf14e' => '　', // [未使用]
		'wf14f' => '　', // [未使用]
		'wf150' => $this->pictograms['se411'], // 泣き顔
		'wf151' => '　', // [未使用]
		'wf152' => '　', // [未使用]
		'wf153' => '　', // [未使用]
		'wf154' => '　', // [未使用]
		'wf155' => '　', // [未使用]
		'wf156' => '　', // [未使用]
		'wf157' => '　', // [未使用]
		'wf158' => '　', // [未使用]
		'wf159' => '　', // [未使用]
		'wf15a' => '　', // [未使用]
		'wf15b' => '　', // [未使用]
		'wf15c' => '　', // [未使用]
		'wf15d' => '　', // [未使用]
		'wf15e' => '　', // [未使用]
		'wf15f' => '　', // [未使用]
	);
	$translated = apply_filters('ktai_pictogram_table', $translated, __CLASS__, $this->charset);
	$buffer = preg_replace(
		'!<img localsrc="([^"]+)"( alt="(' . KtaiStyle::DOUBLE_QUOTED_STRING_REGEX . ')")?[^/>]*/?' . '>!se', // <?php /* syntax hilighting fix */
		'isset($translated["$1"]) ? $translated["$1"] : ("$3" ? "$3" : "〓")', 
		$buffer);
	$entities = array(
		'&spades;' => $this->pictograms['se20e'],
		'&#9824;'  => $this->pictograms['se20e'],
		'&#x2660;' => $this->pictograms['se20e'],
		'&clubs;'  => $this->pictograms['se20f'],
		'&#9827;'  => $this->pictograms['se20f'],
		'&#x2663;' => $this->pictograms['se20f'],
		'&hearts;' => $this->pictograms['se20c'],
		'&#9829;'  => $this->pictograms['se20c'],
		'&#x2665;' => $this->pictograms['se20c'],
		'&#9825;'  => $this->pictograms['se022'], // WHITE HEART
		'&#x2661;' => $this->pictograms['se022'], // WHITE HEART
		'&diams;'  => $this->pictograms['se20d'],
		'&#9830;'  => $this->pictograms['se20d'],
		'&#x2666;' => $this->pictograms['se20d'],
		'&#12336;' => '～～', // WAVY DASH
		'&#x3030;' => '～～', // WAVY DASH

	);
	$buffer = str_replace(array_keys($entities), $entities, $buffer);

	// ----- shrink escape sequences -----
	$count = version_compare(phpversion(), '5.1', '>=');
	while ($count) {
		$buffer = preg_replace("/(\x1b\\\$[A-Z])([!-z]+)\x0f\\1/", '$1$2', $buffer, -1, $count); // available after PHP 5.1.0
	}
	return $buffer;
}

/* ==================================================
 * @param	string  $buffer
 * @return	string  $buffer
 */
public function shrink_post_split($buffer) {
	return parent::shrink_post_split($buffer);
}

/* ==================================================
 * @param	string  $buffer
 * @return	string  $buffer
 */
public function pickup_pics($buffer) {
	$buffer = $this->pickup_pics_webcode($buffer);
	$buffer = $this->pickup_pics_shift_jis($buffer);
	return $buffer;
}

/* ==================================================
 * @param	string  $buffer
 * @return	string  $buffer
 */
private function pickup_pics_webcode($buffer) {
	$seq_index = array('G' => '0', 'E' => '1', 'F' => '2', 'O' => '3', 'P' => '4', 'Q' => '5');
	for ($offset = 0 , $replace = 'X' ;
	     preg_match('/\x1b.([GEFOPQ])([!-z]+)(\x0f|$)/', $buffer, $webcode, PREG_OFFSET_CAPTURE, $offset) ; 
	     $offset += strlen($replace)) 
	{
		$orig    = $webcode[0][0];
		$offset  = $webcode[0][1];
		$seq     = $webcode[1][0];
		$chars   = $webcode[2][0];
		$replace = '';
		for ($i = 0 ; $i < strlen($chars) ; $i++) {
			if (ord($char[$i]) - 32 <= $this->num_chars[$seq]) {
				$replace .= sprintf('<img localsrc="se%d%02x" />', $seq_index[$seq], ord($chars[$i]) - 32);
			} else {
				$replace .= sprintf('<img localsrc="s" alt="[ESC$%s%dSI]" />', $seq, ord($chars[$i]));
			}
		}
		$buffer = substr_replace($buffer, $replace, $offset, strlen($orig));
	}
	return $buffer;
}

/* ==================================================
 * @param	string  $buffer
 * @return	string  $buffer
 */
private function pickup_pics_shift_jis($buffer) {
	if ( !isset($this->pictogram_flipped) ) {
		$this->pictogram_flipped = array_flip($this->pict_sjis);
		if ( !$this->pictogram_flipped ) {
			return $buffer;
		}
	}
	global $Ktai_Style;
	$replaced = $Ktai_Style->encode->regex_replace(
		"([\xf7\x40-\xf7\x5b]|[\xf7\x5d-\xf7\xfc]|[\xf9\x40-\xf9\x5b]|[\xf9\x5d-\xf9\xfc]|[\xfb\x40-\xfb\x5b]|[\xfb\x5d-\xfb\xfc])", 
		'isset($this->pictogram_flipped["\1"]) ? 
		"<img localsrc=\"" . $this->pictogram_flipped["\1"] . "\" />" : 
		"<img localsrc=\"s\" alt=\"" . "[0x" . bin2hex("\1") . "]\" />"', 
		$buffer, $this->charset, 'e');
	if ($replaced) {
		$replaced = $Ktai_Style->encode->regex_replace("\xf7\x5c", '<img localsrc="' . $this->pictogram_flipped["\xf7\x5c"] . '" />', $replaced, $this->charset);
		$replaced = $Ktai_Style->encode->regex_replace("\xf9\x5c", '<img localsrc="' . $this->pictogram_flipped["\xf9\x5c"] . '" />', $replaced, $this->charset);
		$replaced = $Ktai_Style->encode->regex_replace("\xfb\x5c", '<img localsrc="' . $this->pictogram_flipped["\xfb\x5c"] . '" />', $replaced, $this->charset);
	}
	return $replaced ? $replaced : $buffer;
}

// ===== End of class ====================
}

/* ==================================================
 *   KtaiService_Softbank_PDC class
 *   The service is stopped, but need for mobile search engine
   ================================================== */

class KtaiService_Softbank_PDC extends KtaiService_Softbank {

/* ==================================================
 * @param	string  $user_agent
 * @return	object  $this
 */
public function __construct($user_agent) {
	parent::__construct($user_agent);
	// http://creation.mb.softbank.jp/web/web_pic_about.html
	$p = 0;
	foreach ($this->num_chars as $s => $n) {
		for ($i = 1 ; $i <= $n ; $i++) {
			$this->pictograms[sprintf('se%d%02x', $p, $i)] = "\x1b\$$s" . chr(32 + $i) . "\x0f";
		}
		$p++;
	}

	$this->theme         = ks_option('ks_theme_sb_pdc');
	$this->type          = 'PDC';
	$this->flat_rate     = false;
	$this->admin_enabled = false;
	preg_match('!^J-(PHONE|EMULATOR)/(\d\.\d+)/([-_.a-zA-Z0-9]+)/?(SN([-_.a-zA-Z0-9]*) )?!', $user_agent, $specs);
	if ( isset($_SERVER['HTTP_X_JPHONE_MSNAME']) ) {
		$this->term_name = $_SERVER['HTTP_X_JPHONE_MSNAME'];
	} else {
		$this->term_name = isset($specs[3]) ? $specs[3] : NULL;
	}
	$this->term_ID = isset($specs[5]) ? $specs[5] : NULL;
	$this->cookie_available = false;
	$this->ext_css_available = false;
	$this->available_js_version = false;
	if (isset($_SERVER['x-jphone-display'])) {
		list($this->screen_width, $this->screen_height) = array_map('intval', explode('*', $_SERVER['x-jphone-display']));
	}
	$this->textarea_size = 6000;
	$this->page_size = 6000;
	if ($specs[2] < 4.0) {
		$this->cache_size = 6000;
		$this->sub_ID_available = false;
		$this->require_id_msg = "ERROR: Can't post a comment. We request your terminal's manufacture number but your phone does not available to trasmit it.";
	} else {
		$this->cache_size = 12000;
		$this->sub_ID_available = true;
		$this->require_id_msg = "ERROR: Please allow transmission of user infomation or your terminal's manifacture number.\nGo Yahoo! Japan &gt; My Softbank (User Support) &gt; Misc Application &gt; Transmission of User Infomation / Transmission of Manifacture Number.";
	}
	if ( $this->sub_ID_available && isset($_SERVER['HTTP_X_JPHONE_UID']) ) {
		$this->sub_ID = stripslashes($_SERVER['HTTP_X_JPHONE_UID']);
	 } else {
		$this->sub_ID = NULL;
	 }
	$this->preamble   = '';
	$this->xhtml_head = '';
	return;
}

/* ==================================================
 * @param	string  $buffer
 * @return	string  $buffer
 */
public function shrink_pre_split($buffer) {
	$buffer = preg_replace('!<h([1-6])([^>]*)>(.*?)</h\\1>!s', '<div$2><p>$3</p></div>', $buffer);
	$buffer = preg_replace('!<img([^>]*?) src=([\'"])([^>]*?)\.gif\\2!s', '<img$1 src=$2$3.png$2', $buffer); //"
	$buffer = preg_replace('!<a([^>]*?) href=([\'"])([^>]*?)\.gif\\2!s', '<a$1 href=$2$3.png$2', $buffer); //"
	return parent::shrink_pre_split($buffer);
}

/* ==================================================
 * @param	string  $buffer
 * @return	string  $buffer
 */
public function shrink_post_split($buffer) {
	$buffer = str_replace('&nbsp;', ' ', $buffer);
	$buffer = preg_replace('!\s*</(li|dt|dd|option)>\s*!', '', $buffer);
	$buffer = preg_replace('! ?/>!', '>', $buffer);
/*	$buffer = preg_replace('!<([-~_= a-zA-Z0-9%.,:;\'"/#*+]+?) ?/>!', '<$1>', $buffer); */
	return parent::shrink_post_split($buffer);
}

// ===== End of class ====================
}

/* ==================================================
 *   KtaiService_Softbank_3G class
   ================================================== */

class KtaiService_Softbank_3G extends KtaiService_Softbank {

/* ==================================================
 * @param	string  $user_agent
 * @return	object  $this
 */
public function __construct($user_agent) {
	parent::__construct($user_agent);
	$p = 0;
	foreach ($this->num_chars as $s => $n) {
		for ($i = 1 ; $i <= $n ; $i++) {
			$index = sprintf('se%d%02x', $p, $i);
			$this->pictograms[$index] = $this->pict_sjis[$index];
		}
		$p++;
	}

	$this->theme         = ks_option('ks_theme_sb_3g');
	$this->type          = '3G';
	$this->flat_rate     = true;
	$this->admin_enabled = true;
	if ( isset($_SERVER['HTTP_X_JPHONE_MSNAME']) ) {
		$this->term_name = $_SERVER['HTTP_X_JPHONE_MSNAME'];
	} else {
		$this->term_name = NULL;
	}
	if (preg_match('!^(Vodafone|SoftBank|[VS]emulator)/\d\.\d+/([-_.a-zA-Z0-9]+)/[-_.a-zA-Z0-9]+(/SN([-_.a-zA-Z0-9]*) )?!', $user_agent, $specs)) {
		$this->term_name = $this->term_name ? $this->term_name : $specs[2];
		$this->term_ID = isset($specs[4]) ? $specs[4] : NULL;
	} elseif (preg_match('!^MOT(EMULATOR)?-([CV]\d+)!', $user_agent, $specs)) {
		$names = array('C980' => '702MO', 'V980' => '702sMO');
		$this->term_name = isset($names[$specs[2]]) ? $names[$specs[2]] : NULL;
	}
	$this->sub_ID_available = is_ssl() ? false : true;
	if ( $this->sub_ID_available && isset($_SERVER['HTTP_X_JPHONE_UID']) ) {
		$this->sub_ID = stripslashes($_SERVER['HTTP_X_JPHONE_UID']);
	} else {
		$this->sub_ID = NULL;
	}
	$this->cookie_available = true;
	$this->ext_css_available = true;
	$this->available_js_version = '3.0';
	if (isset($_SERVER['x-s-display-info']) && preg_match('!^(\d+)\*(\d+)/!', $_SERVER['x-s-display-info'] , $sizes) ) {
		$this->screen_width  = $sizes[1];
		$this->screen_height = $sizes[2];
	} elseif (isset($_SERVER['x-jphone-display'])) {
		list($this->screen_width, $this->screen_height) = array_map('intval', explode('*', $_SERVER['x-jphone-display']));
	}
	$this->textarea_size = 20000;
	$this->page_size  = 20000;
	$this->cache_size = 300000;
	$this->require_id_msg = "ERROR: Please allow transmission of user infomation or your terminal's manifacture number.\nGo Yahoo! Japan &gt; My Softbank (User Support) &gt; Misc Application &gt; Transmission of User Infomation.\nGo Yahoo! Keitai &gt; Common Settings &gt; Security Settings &gt; Manufacture Number.";
	$this->preamble   = '<?xml version="1.0" encoding="__CHARSET__"?>
<!DOCTYPE html PUBLIC "-//J-PHONE//DTD XHTML Basic 1.0 Plus//EN" "xhtml-basic10-plus.dtd">'; // <?php /* syntax hilighting fix */
	$this->xhtml_head = '<html>';
	add_action('ktai_wp_head', array($this, 'paragraph_margin') );
	return;
}

/* ==================================================
 * @param	string  $buffer
 * @return	string  $buffer
 */
public function shrink_post_split($buffer) {
	if ($this->mime_type == 'application/xhtml+xml') {
		$buffer = $this->input_to_style($buffer);
	}
	return parent::shrink_post_split($buffer);
}

/* ==================================================
 * @param	none
 * @return	none
 * @since	2.0.0
 */
public function paragraph_margin() {
	echo '<style type="text/css"><![CDATA[ p {margin:0.5em 0;} ]]></style>' . "\n";
}


// ===== End of class ====================
}
?>